//! Page definitions for the registry.
//!
//! This file contains all page entries for PAGE_REGISTRY.
//! Edit this file to add, remove, or modify pages.

use std::collections::HashMap;
use std::sync::LazyLock;

use super::{alias, datetime, page, PageInfo, UpvoteConfig};

const DEPRECATED_BANNER: &str = "<div class=\"deprecated-banner\">This page has been deprecated. The code/information below may no longer be maintained.</div>";

/// Registry for all "normal" pages on the site. See main.rs for special routes.
///
/// Specify:
///     handler: e.g. `about` expands to crate::pages::about::Handler
///     slug: the URL slug
///     title: the page title (or "" to use default)
///     description: the HTML metadata description ("" for default)
///     keywords: keywords for HTML metadata ("" for default)
///     legacy_hit_count_id: file path in the old PHP codebase, key for hit counter
///     upvote: upvote metadata (specify this for new pages and it just works)
///
/// Or use alias! to create a redirect.
///
/// For new pages, set legacy_hit_count_id to the slug (TODO: automatically use
/// the slug) when legacy_hit_count_id is unset.
///
/// Slugs are matched case-insensitively, so do not add pages with slugs that
/// differ only by case. You may still use uppercase characters in slugs,
/// the case as defined below will be used for generating canonical URLs.
///
/// Empty string "" slug is the home page.
pub static PAGE_REGISTRY: LazyLock<HashMap<&'static str, PageInfo>> = LazyLock::new(|| {
    let pages: &[PageInfo] = &[
        // ===== Home page =====
        page! {
            handler: home,
            slug: "",
            title: "Defuse Security Research and Development",
            description: "Defuse Security. Home of PIE Bin, TRENT, and more...",
            keywords: "defuse security, encryption, privacy, programming, code, research",
            legacy_hit_count_id: "pages/home.html",
            upvote: None,
        },

        // ===== Home page aliases =====
        alias!("index" => ""),
        alias!("index.html" => ""),
        alias!("index.php" => ""),

        // ===== All pages =====
        page! {
            handler: all_pages,
            slug: "all-pages",
            title: "",
            description: "A list of all pages on defuse.ca, sorted by popularity.",
            keywords: "",
            legacy_hit_count_id: "pages/all-pages.php",
            upvote: None,
        },

        // ===== Main pages =====
        page! {
            handler: about,
            slug: "about",
            title: "",
            description: "About Defuse Security.",
            keywords: "",
            legacy_hit_count_id: "pages/about.html",
            upvote: None,
        },
        page! {
            handler: contact,
            slug: "contact",
            title: "Defuse Security's Contact Information",
            description: "Defuse Security's contact information.",
            keywords: "",
            legacy_hit_count_id: "pages/contact.html",
            upvote: None,
        },
        // I've linked to my PGP key this way
        alias!("key" => "contact"),
        page! {
            handler: security_contact_vulnerability_disclosure,
            slug: "security-contact-vulnerability-disclosure",
            title: "Security Contact and Vulnerability Disclosure",
            description: "How to disclose vulnerabilities in Defuse Security services",
            keywords: "full disclosure, security contact, vulnerabilities",
            legacy_hit_count_id: "pages/security-contact-vulnerability-disclosure.php",
            upvote: None,
        },
        page! {
            handler: vimrc,
            slug: "vimrc",
            title: "My .vimrc - Defuse Security",
            description: "My Vim configuration file",
            keywords: "vim, vimrc, vim configuration",
            legacy_hit_count_id: "pages/vimrc.php",
            upvote: Some(UpvoteConfig {
                id: "myvimrc",
                category: "defuse_misc",
                title: Some("My Vim Configuration"),
                description: Some("My configuration of the Vim text and code editor."),
            }),
        },
        page! {
            handler: honestyware,
            slug: "honestyware",
            title: "Honestyware - The right way to sell software.",
            description: "Honestyware is a revolutionary way to sell software that embraces piracy.",
            keywords: "honestyware, free software, trust user",
            legacy_hit_count_id: "pages/honestyware.php",
            upvote: Some(UpvoteConfig {
                id: "honestyware",
                category: "defuse_misc",
                title: Some("Honestyware"),
                description: Some("A philosophy for selling software and other digital content on the internet."),
            }),
        },
        page! {
            handler: reading_list,
            slug: "reading-list",
            title: "Reading List - Defuse Security",
            description: "Everything I have read so far.",
            keywords: "reading list, infosec",
            legacy_hit_count_id: "pages/reading-list.php",
            upvote: Some(UpvoteConfig {
                id: "reading_list",
                category: "defuse_misc",
                title: Some("Reading List"),
                description: Some("A list of the books I have read."),
            }),
        },
        page! {
            handler: misc::miscellaneous,
            slug: "miscellaneous",
            title: "Miscellaneous Pages",
            description: "Miscellaneous pages on Defuse Security, sorted by popularity.",
            keywords: "",
            legacy_hit_count_id: "miscellaneous",
            upvote: None,
        },
        page! {
            handler: pdftribute,
            slug: "pdftribute",
            title: "#pdftribute",
            description: "#pdftribute",
            keywords: "#pdftribute",
            legacy_hit_count_id: "pages/pdftribute.php",
            upvote: None,
            date: datetime("2013-01-15T04:51:55+00:00"),
        },

        // ===== Services =====
        alias!("services" => "software-security-auditing"),
        page! {
            handler: services::checksums,
            slug: "checksums",
            title: "Online Text and File Hash Calculator - MD5, SHA1, SHA256, SHA512, WHIRLPOOL Hash Calculator - Defuse Security",
            description: "Online Hash Tool. Calculate hash of file or text. MD5, SHA1, SHA256, SHA512 and more...",
            keywords: "file hasher, online, hash, md5, sha256, sha1, text hash, checksum",
            legacy_hit_count_id: "pages/services/checksums.php",
            upvote: Some(UpvoteConfig {
                id: "onlinechecksums",
                category: "defuse_services",
                title: Some("Online Hash Calculator"),
                description: Some("A tool for computing hashes (MD5, SHA1, SHA2, etc.) of text and files."),
            }),
        },
        page! {
            handler: services::big_number_calculator,
            slug: "big-number-calculator",
            title: "Online Big Number Calculator",
            description: "Calculate enormous mathematical equations from within your browser.",
            keywords: "big number calculator, online calculator, bigint, galactic calculator",
            legacy_hit_count_id: "pages/services/big-number-calculator.php",
            upvote: Some(UpvoteConfig {
                id: "bignumbercalculator",
                category: "defuse_services",
                title: Some("Big Number Calculator"),
                description: Some("A tool for calculating with huge numbers."),
            }),
        },
        page! {
            handler: services::html_sanitize,
            slug: "html-sanitize",
            title: "Online HTML Sanitizer Tool - htmlspecialchars - Defuse Security",
            description: "Convert text containing special characters into proper HTML.",
            keywords: "html sanitizer, htmlspecialchars, htmlencode",
            legacy_hit_count_id: "pages/services/html-sanitize.php",
            upvote: Some(UpvoteConfig {
                id: "onlinehtmlsanitize",
                category: "defuse_services",
                title: Some("HTML Escape Tool"),
                description: Some("A tool for HTML-escaping text so that it looks and behaves exactly like it does in a text editor."),
            }),
        },
        page! {
            handler: services::online_x86_assembler,
            slug: "online-x86-assembler",
            title: "Online x86 and x64 Intel Instruction Assembler",
            description: "Easily find out which bytes your x86 ASM instructions assemble to.",
            keywords: "assembler, opcode finder, opcode lookup, online assembler, x86, intel",
            legacy_hit_count_id: "pages/services/online-x86-assembler.php",
            upvote: Some(UpvoteConfig {
                id: "onlinex86assembler",
                category: "defuse_services",
                title: Some("Online x86 / x64 Assembler"),
                description: Some("Assemble x86 and x64 code in your browser!"),
            }),
        },
        page! {
            handler: services::pastebin,
            slug: "pastebin",
            title: "Encrypted Pastebin - Keep your data private and secure! - Defuse Security",
            description: "An Encrypted, Anonymous, Secure, and PRIVATE Pastebin. Send large amounts of text to your friends without it being leaked onto the internet!",
            keywords: "private pastebin, encrypted pastebin, secure pastebin, anonymous pastebin, privacy",
            legacy_hit_count_id: "pages/services/pastebin.html",
            upvote: Some(UpvoteConfig {
                id: "pastebin",
                category: "defuse_services",
                title: Some("PIE Bin"),
                description: Some("A pastebin with both client-side and server-side encryption."),
            }),
        },
        page! {
            handler: services::quantum_computer_time_capsule,
            slug: "quantum-computer-time-capsule",
            title: "Send a Message to the Future (Digital Time Capsule)",
            description: "Save a message that will become readable after quantum computers are built.",
            keywords: "digital time capsule, quantum computers",
            legacy_hit_count_id: "pages/services/quantum-computer-time-capsule.php",
            upvote: Some(UpvoteConfig {
                id: "quantumcomputertimecapsule",
                category: "defuse_services",
                title: Some("Send a Message to the Future"),
                description: Some("Save a message that will become readable after quantum computers are built."),
            }),
        },
        page! {
            handler: services::software_security_auditing,
            slug: "software-security-auditing",
            title: "Cryptography & Software Security Auditing",
            description: "Get your software audited for security bugs.",
            keywords: "software security, exploits, auditing",
            legacy_hit_count_id: "pages/services/software-security-auditing.php",
            upvote: None,
        },
        alias!("audits/" => "software-security-auditing"),
        page! {
            handler: services::trent,
            slug: "trustedthirdparty",
            title: "TRENT - FREE Third party Drawing Service - Defuse Security",
            description: "TRENT, the trusted random number generator for contests and drawings.",
            keywords: "contest drawing, third party, trusted, lottory, trent, random number generator",
            legacy_hit_count_id: "pages/services/trustedthirdparty.php",
            upvote: Some(UpvoteConfig {
                id: "trent",
                category: "defuse_services",
                title: Some("TRENT - Trusted Random Entropy"),
                description: Some("A free trusted third party random number generator."),
            }),
        },
        alias!("trent" => "trustedthirdparty"),

        // ===== Research =====
        page! {
            handler: research::asuskeyboarddefect,
            slug: "asuskeyboarddefect",
            title: "ASUS G50 G51 Keyboard Problem: Backspace, P, and 1 keys don't work. - Defuse Security",
            description: "Solution to the keyboard problem for the ASUS G50, G51, and G51VX series laptops.",
            keywords: "asus keyboard, g series, g51, g50, g51vx, backspace, p, q, keys, broken",
            legacy_hit_count_id: "pages/research/asuskeyboarddefect.html",
            upvote: Some(UpvoteConfig {
                id: "asuskeyboarddefect",
                category: "defuse_research",
                title: Some("Asus G Series Keyboard Design Error"),
                description: Some("Fixing a problem with the keyboard in an ASUS laptop."),
            }),
        },
        alias!("keyboarddefect" => "asuskeyboarddefect"),
        page! {
            handler: research::auditician,
            slug: "auditician",
            title: "Auditician: Automated Security Audits with Claude Code",
            description: "Claude Code agents and audit process descriptions for performing security audits automatically.",
            keywords: "auditician, automated security audit, claude code, ai security audit, agents",
            legacy_hit_count_id: "auditician",
            upvote: Some(UpvoteConfig {
                id: "auditician",
                category: "defuse_research",
                title: Some("Auditician: Automated Security Audits with Claude Code"),
                description: Some("Claude Code agents and audit process descriptions for performing security audits automatically."),
            }),
            date: datetime("2026-08-15T12:58:50-06:00"),
        },
        page! {
            handler: research::bitcoin_pool_ddos,
            slug: "bitcoin-pool-ddos",
            title: "BitCoin Centralization - DDoS Attacks on Pools & Mt. Gox Hacked - Defuse Security",
            description: "Centralization is harmful to the BitCoin network and community.",
            keywords: "bitcoin, ddos, denial of service, pool, mining, mtgox, centralization, hacked",
            legacy_hit_count_id: "pages/research/bitcoin-pool-ddos.html",
            upvote: Some(UpvoteConfig {
                id: "bitcoinpoolddos",
                category: "defuse_research",
                title: Some("Centralization is Killing Bitcoin"),
                description: Some("An article on Bitcoin, centralization, and DDoS attacks."),
            }),
            date: datetime("2011-06-22T12:00:00-07:00"),
            banner: Some("<div class=\"deprecated-banner\">This article is outdated.</div>"),
        },
        page! {
            handler: research::blind_birthday_attack,
            slug: "blind-birthday-attack",
            title: "Blind Birthday Attack",
            description: "Birthday attack without seeing the values.",
            keywords: "birthday attack, blind, double hmac, cryptography",
            legacy_hit_count_id: "pages/research/blind-birthday-attack.php",
            upvote: Some(UpvoteConfig {
                id: "blindbirthdayattack",
                category: "defuse_research",
                title: Some("Blind Birthday Attack"),
                description: Some("A birthday attack without knowing what the collision actually is."),
            }),
            date: datetime("2014-07-13T12:00:00-07:00"),
        },
        page! {
            handler: research::bochs_hacking_guide,
            slug: "bochs-hacking-guide",
            title: "Bochs Hacking Guide",
            description: "Hacking the Bochs x86 CPU emulator. Changing and adding instructions.",
            keywords: "bochs, emulator, cpu, architecture, x86, intel, ia-32",
            legacy_hit_count_id: "pages/research/bochs-hacking-guide.php",
            upvote: Some(UpvoteConfig {
                id: "bochshacking",
                category: "defuse_research",
                title: Some("Bochs Hacking Guide"),
                description: Some("Hacking the Bochs x86 CPU emulator."),
            }),
            date: datetime("2014-01-02T12:00:00-07:00"),
        },
        page! {
            handler: research::cbcmodeiv,
            slug: "cbcmodeiv",
            title: "Should CBC Mode Initialization Vector Be Secret - Defuse Security",
            description: "Should the initialization vector used for CBC mode be kept secret?",
            keywords: "cbc mode, encryption, initialization vector, iv, secret, secure",
            legacy_hit_count_id: "pages/research/cbcmodeiv.html",
            upvote: Some(UpvoteConfig {
                id: "cbcmodeiv",
                category: "defuse_research",
                title: Some("Encryption - CBC Mode IV: Secret or Not?"),
                description: Some("Should the IV in CBC mode be kept secret?"),
            }),
            date: datetime("2013-09-08T12:00:00-07:00"),
        },
        page! {
            handler: research::concentration_bounds_from_parallel_repetition_theorems,
            slug: "concentration-bounds-from-parallel-repetition-theorems",
            title: "Concentration Bounds from Parallel Repetition Theorems",
            description: "My master's thesis, showing how concentration bounds can be derived from parallel repetition theorems for nonlocal games and interactive proofs.",
            keywords: "concentration bounds, parallel repetition theorems, quantum information, symmetric key strengthening",
            legacy_hit_count_id: "pages/research/concentration-bounds-from-parallel-repetition-theorems.php",
            upvote: Some(UpvoteConfig {
                id: "mastersthesis",
                category: "defuse_research",
                title: Some("Concentration Bounds from Parallel Repetition Theorems"),
                description: Some("My master's thesis, showing how concentration bounds can be derived from parallel repetition theorems for nonlocal games and interactive proofs."),
            }),
            date: datetime("2018-08-23T12:00:00-07:00"),
        },
        page! {
            handler: research::cracking_synergy_bad_cryptography,
            slug: "cracking-synergy-bad-cryptography",
            title: "Cracking Synergy's Bad Cryptography",
            description: "A tool to crack Synergy's homebrew cryptography",
            keywords: "synergy, cryptography, crack, homebrew, keyboard sharing, mouse sharing",
            legacy_hit_count_id: "pages/research/cracking-synergy-bad-cryptography.php",
            upvote: Some(UpvoteConfig {
                id: "synergy_cracking",
                category: "defuse_research",
                title: Some("Cracking Synergy's Bad Cryptography"),
                description: Some("A tool to crack Synergy's homebrew cryptography."),
            }),
            date: datetime("2013-07-20T12:00:00-07:00"),
        },
        page! {
            handler: research::exploiting_cpp_vtables,
            slug: "exploiting-cpp-vtables",
            title: "Instance Replacement: Exploiting C++ VTABLES",
            description: "How C++ classes are represented, how VTABLES work, and how to exploit them.",
            keywords: "vtable overwriting, vtable exploit, buffer overflow, vulnerability",
            legacy_hit_count_id: "pages/research/exploiting-cpp-vtables.php",
            upvote: Some(UpvoteConfig {
                id: "cppvtables",
                category: "defuse_research",
                title: Some("Exploiting C++ VTABLES: Instance Replacement"),
                description: Some("Use a memory corruption vulnerability to change an instance of class A into an instance of class B."),
            }),
            date: datetime("2013-05-11T12:00:00-07:00"),
        },
        page! {
            handler: research::in_browser_port_scanning,
            slug: "in-browser-port-scanning",
            title: "Port Scanning Local Network From a Web Browser",
            description: "Malicious web pages can port scan your local network.",
            keywords: "browser, port scan, security",
            legacy_hit_count_id: "pages/research/in-browser-port-scanning.php",
            upvote: Some(UpvoteConfig {
                id: "inbrowserportscanner",
                category: "defuse_research",
                title: Some("Timing Side Channel Port Scanner in the Browser"),
                description: Some("How web pages can use a timing side channel to \"scan\" your local network."),
            }),
            date: datetime("2015-04-12T12:00:00-07:00"),
        },
        page! {
            handler: research::filesystem_events_ntfs_permissions,
            slug: "filesystem-events-ntfs-permissions",
            title: "File System Events Disclose NTFS Protected Folder Contents - Defuse Security",
            description: "Obtain list of files in folder protected with NTFS permissions via filesystem events",
            keywords: "",
            legacy_hit_count_id: "pages/research/filesystemevents.html",
            upvote: Some(UpvoteConfig {
                id: "filesystemevents",
                category: "defuse_research",
                title: Some("File System Events Leak Folder Contents"),
                description: Some("An information disclosure vulnerability in Windows shared folders that lets you see what's in folers you can't access."),
            }),
            date: datetime("2011-06-12T12:00:00-07:00"),
        },
        page! {
            handler: research::flush_reload_side_channel,
            slug: "flush-reload-side-channel",
            title: "Implications of the FLUSH+RELOAD Side-Channel Attack",
            description: "The FLUSH+RELOAD side-channel attack breaks security in multi-user environments.",
            keywords: "FLUSH+RELOAD, side channel attack, multi-user security",
            legacy_hit_count_id: "pages/research/flush-reload-side-channel.php",
            upvote: Some(UpvoteConfig {
                id: "flushreload",
                category: "defuse_research",
                title: Some("FLUSH+RELOAD: Multi-User Systems are Doomed"),
                description: Some("The FLUSH+RELOAD side-channel attack breaks the security of multi-user systems."),
            }),
            date: datetime("2013-09-15T12:00:00-07:00"),
        },
        page! {
            handler: research::godel_second_incompleteness_theorem_by_turing_machines,
            slug: "godel-second-incompleteness-theorem-by-turing-machines",
            title: "A Simple Proof of Gödel's Second Incompleteness Theorem Using Turing Machines",
            description: "Proving Gödel's second incompleteness theorem in a simpler way using Turing machines.",
            keywords: "godel, second incompleteness theorem, simple proof, turing machines, computability",
            legacy_hit_count_id: "pages/research/godel-second-incompleteness-theorem-by-turing-machines.php",
            upvote: Some(UpvoteConfig {
                id: "godelsecondtms",
                category: "defuse_research",
                title: Some("A Simple Proof of Gödel's Second Incompleteness Theorem Using Turing Machines"),
                description: Some("Proving Gödel's second incompleteness theorem in a way that should be understandable to anyone who understands the proof that the halting problem is undecidable."),
            }),
            date: datetime("2024-02-09T12:00:00-07:00"),
            math: true,
        },
        page! {
            handler: research::how_do_we_model_this_robot,
            slug: "how-do-we-model-this-robot",
            title: "How do we model this robot?",
            description: "Modeling Computational Ability and Informational Ability.",
            keywords: "langsec, robot, modeling, computational, informational",
            legacy_hit_count_id: "pages/research/how-do-we-model-this-robot.php",
            upvote: Some(UpvoteConfig {
                id: "howdowemodelthisrobot",
                category: "defuse_research",
                title: Some("How do we model this robot?"),
                description: Some("The difference between Computational Ability and Informational Ability"),
            }),
            date: datetime("2015-03-25T12:00:00-07:00"),
        },
        page! {
            handler: research::instruction_filters,
            slug: "instruction-filters",
            title: "Instruction Filters as an Exploitation Defense",
            description: "Disabling CPU instructions to thwart ROP and other attacks.",
            keywords: "instruction set filters, insfilter, research",
            legacy_hit_count_id: "pages/research/instruction-filters.php",
            upvote: Some(UpvoteConfig {
                id: "instructionfilters",
                category: "defuse_research",
                title: Some("Instruction Filters as an Exploitation Defense"),
                description: Some("Disabling CPU instructions to thwart ROP and other attacks."),
            }),
            date: datetime("2014-01-02T06:46:02-07:00"),
        },
        page! {
            handler: research::is_security_local,
            slug: "is-security-local",
            title: "Is Security Local?",
            description: "Is security a locally-verifiable property of computation?",
            keywords: "langsec, security, locality, verification",
            legacy_hit_count_id: "pages/research/is-security-local.php",
            upvote: Some(UpvoteConfig {
                id: "issecuritylocal",
                category: "defuse_research",
                title: Some("Is Security Local?"),
                description: Some("Is security a locally-verifiable property of computation?"),
            }),
            date: datetime("2015-05-27T12:00:00-07:00"),
        },
        page! {
            handler: research::onedetection,
            slug: "onedetection",
            title: "The PUP Confusion Antivirus Detection Evasion Technique - Defuse Security",
            description: "The PUP Confusion Antivirus Detection Evasion Technique. Multiple detections per file.",
            keywords: "antivirus, single detection, only one detection, can't detect more than one, multiple virus, two viruses in one file",
            legacy_hit_count_id: "pages/research/onedetection.html",
            upvote: Some(UpvoteConfig {
                id: "pupconfusion",
                category: "defuse_research",
                title: Some("The PUP Confusion Technique"),
                description: Some("Undetecting malware by making it look like a Potentially Unwanted Program (PUP)."),
            }),
            date: datetime("2011-06-12T12:00:00-07:00"),
        },
        page! {
            handler: research::password_hashing_after_phc,
            slug: "password-hashing-after-phc",
            title: "Password Hashing After PHC",
            description: "Giving authenticators an advantage over password crackers with cache.",
            keywords: "password hashing competition, key stretching, caching",
            legacy_hit_count_id: "pages/research/password-hashing-after-phc.php",
            upvote: Some(UpvoteConfig {
                id: "passhashingphc",
                category: "defuse_research",
                title: Some("Password Hashing After the PHC"),
                description: Some("Giving authenticators an advantage over password crackers with cache."),
            }),
            date: datetime("2013-07-26T12:00:00-07:00"),
        },
        page! {
            handler: research::plausible_reason_p_noteq_np_is_hard_to_prove,
            slug: "plausible-reason-p-noteq-np-is-hard-to-prove",
            title: "A Plausible Reason It's So Hard To Prove P!=NP",
            description: "Attempting to show why P!=NP is hard to prove using hash functions.",
            keywords: "p versus np, hard to prove, hash functions, language collisions",
            legacy_hit_count_id: "pages/research/plausible-reason-p-noteq-np-is-hard-to-prove.php",
            upvote: Some(UpvoteConfig {
                id: "plausiblepneqnpprove",
                category: "defuse_research",
                title: Some("A Plausible Reason It's So Hard To Prove P!=NP"),
                description: Some("Attempting to show why P!=NP is hard to prove using hash functions."),
            }),
            date: datetime("2022-01-05T12:00:00-07:00"),
        },
        page! {
            handler: research::password_policy_hall_of_shame,
            slug: "password-policy-hall-of-shame",
            title: "Password Policy Hall of SHAME - Defuse Security",
            description: "List of websites and services that impose password restrictions and may be storing passwords in plaintext.",
            keywords: "hall of shame, password hall of shame, plaintext, password restrictions, maximum password length, restriction, insecure",
            legacy_hit_count_id: "pages/research/hallofshame.php",
            upvote: None,
            date: datetime("2011-07-07T23:23:54+00:00"),
        },
        alias!("pphos" => "password-policy-hall-of-shame"),
        page! {
            handler: research::race_conditions_in_web_applications,
            slug: "race-conditions-in-web-applications",
            title: "Practical Race Condition (TOCTTOU) Vulnerabilities in Web Applications - Defuse Security",
            description: "Query-level race conditions can lead to serious but hard to find vulnerabilities in web applications.",
            keywords: "",
            legacy_hit_count_id: "pages/research/race-conditions-in-web-applications.php",
            upvote: Some(UpvoteConfig {
                id: "raceconditions",
                category: "defuse_research",
                title: Some("Practical Race Condition Vulnerabilities in Web Applications"),
                description: Some("An example of a web application (PHP) vulnerable to a race condition, and how to fix it."),
            }),
            date: datetime("2011-12-21T12:00:00-07:00"),
        },
        page! {
            handler: research::research,
            slug: "research",
            title: "Defuse Security's Research",
            description: "Research projects by Defuse Security",
            keywords: "",
            legacy_hit_count_id: "pages/research/research.html",
            upvote: None,
        },
        page! {
            handler: research::mitigating_breach_tls_attack_in_php,
            slug: "mitigating-breach-tls-attack-in-php",
            title: "PHP Code for Mitigating the BREACH attack on SSL/TLS.",
            description: "PHP functions for defending secrets against the BREACH attack.",
            keywords: "BREACH, BREACH attack, compression side-channel, php source code",
            legacy_hit_count_id: "pages/research/mitigating-breach-tls-attack-in-php.php",
            upvote: Some(UpvoteConfig {
                id: "breachmitigate",
                category: "defuse_research",
                title: Some("Mitigating BREACH in PHP"),
                description: Some("PHP code for mitigating the BREACH attack."),
            }),
            date: datetime("2013-08-09T12:00:00-07:00"),
        },
        page! {
            handler: research::side_channel_attacks_on_everyday_applications,
            slug: "side-channel-attacks-on-everyday-applications",
            title: "Side-Channel Attacks on Everyday Applications (Black Hat 2016)",
            description: "Data and code for my paper applying FLUSH+RELOAD to break privacy.",
            keywords: "cache side channel, experiment data, flush, reload, privacy",
            legacy_hit_count_id: "pages/research/side-channel-attacks-on-everyday-applications.php",
            upvote: Some(UpvoteConfig {
                id: "side-channel-attacks-on-everyday-applications",
                category: "defuse_research",
                title: Some("Side-Channel Attacks on Everyday Applications"),
                description: Some("My Black Hat USA 2016 talk about the Flush+Reload side channel."),
            }),
            date: datetime("2016-08-03T12:00:00-07:00"),
        },
        alias!("bh2016" => "side-channel-attacks-on-everyday-applications"),
        page! {
            handler: research::security_engineering_safety_critical,
            slug: "security-engineering-learning-from-safety-critical-disciplines",
            title: "Security Engineering: Learning from Safety-Critical Disciplines",
            description: "What the security industry can learn from safety-critical engineering disciplines.",
            keywords: "security engineering, safety-critical, aviation, redundancy, incident investigation",
            legacy_hit_count_id: "security-engineering-learning-from-safety-critical-disciplines",
            upvote: Some(UpvoteConfig {
                id: "security-engineering-learning-from-safety-critical-disciplines",
                category: "defuse_research",
                title: Some("Security Engineering from Safety-Critical Disciplines"),
                description: Some("Useful concepts and methods from safety engineering, applied to computer security."),
            }),
            date: datetime("2023-07-31T12:00:00-07:00"),
        },
        page! {
            handler: research::manual_random_number_generator,
            slug: "manual-random-number-generator",
            title: "Manually Generating Random Numbers",
            description: "Manually generating random numbers for cryptographic use.",
            keywords: "random numbers, true random, csprng, cryptographically secure",
            legacy_hit_count_id: "pages/research/manual-random-number-generator.php",
            upvote: Some(UpvoteConfig {
                id: "manualrng",
                category: "defuse_research",
                title: Some("A Manual Random Number Generator"),
                description: Some("Generating random numbers with paper coins."),
            }),
            date: datetime("2014-01-04T12:00:00-07:00"),
        },
        page! {
            handler: research::microsoft_reads_your_skype_messages,
            slug: "microsoft-reads-your-skype-messages",
            title: "Confirmation of H-Online's Skype Results: Microsoft Visits Links",
            description: "An independent confirmation of Microsoft's skype spying.",
            keywords: "h-online skype, skype spying, microsoft, skype security",
            legacy_hit_count_id: "pages/research/microsoft-reads-your-skype-messages.php",
            upvote: Some(UpvoteConfig {
                id: "skypemitm",
                category: "defuse_research",
                title: Some("Confirmed: Microsoft Visits Links You Send In Skype"),
                description: Some("I sent a link through Skype and Microsoft visted it, confirming The H's claims."),
            }),
            date: datetime("2013-05-16T12:00:00-07:00"),
        },
        page! {
            handler: research::eotp,
            slug: "eotp",
            title: "Encrypting One Time Passwords System - Defuse Security",
            description: "A One Time Password protocol that can be used with encryption.",
            keywords: "encrypting one time passwords, static key, one time password",
            legacy_hit_count_id: "pages/research/eotp.html",
            upvote: Some(UpvoteConfig {
                id: "eotp",
                category: "defuse_research",
                title: Some("Encrypting One Time Passwords (EOTP)"),
                description: Some("EOTP is a cryptographic One Time Password (OTP) protocol designed to provide a static encryption key across login sessions."),
            }),
            banner: Some(DEPRECATED_BANNER),
        },
        page! {
            handler: research::triangle_of_secure_code_delivery,
            slug: "triangle-of-secure-code-delivery",
            title: "Triangle of Secure Code Delivery",
            description: "What's necessary and sufficient for delivering code securely?",
            keywords: "code delivery, triangle, reproducible build, signing",
            legacy_hit_count_id: "pages/research/triangle-of-secure-code-delivery.php",
            upvote: Some(UpvoteConfig {
                id: "trianglesecurecodedelivery",
                category: "defuse_research",
                title: Some("Triangle of Secure Code Delivery"),
                description: Some("Three properties necessary and sufficient for delivering code safely."),
            }),
            date: datetime("2014-07-24T12:00:00-07:00"),
        },
        page! {
            handler: research::truecrypt_plausible_deniability_useless_by_game_theory,
            slug: "truecrypt-plausible-deniability-useless-by-game-theory",
            title: "TrueCrypt's Plausible Deniability (Hidden Volumes) is Theoretically Useless",
            description: "How game theory shows that TrueCrypt's hidden volume feature is provably useless in some scenarios.",
            keywords: "game theory, truecrypt plausible deniability",
            legacy_hit_count_id: "pages/research/truecrypt-plausible-deniability-useless-by-game-theory.php",
            upvote: Some(UpvoteConfig {
                id: "truecryptgametheory",
                category: "defuse_research",
                title: Some("TrueCrypt's Plausible Deniability is Theoretically Useless"),
                description: Some("Why you really ought to have a hidden volume, even if you don't need one."),
            }),
            date: datetime("2013-03-02T12:00:00-07:00"),
        },
        page! {
            handler: research::web_application_security,
            slug: "web-application-security",
            title: "Web Application Security - Defuse Security",
            description: "Why are websites so insecure? What design patterns will help solve these problems?",
            keywords: "web application security, cross site scripting, sql injection, remote code execution, php, asp, scripting",
            legacy_hit_count_id: "pages/research/web-application-security.html",
            upvote: Some(UpvoteConfig {
                id: "webappsec",
                category: "defuse_research",
                title: Some("Data Flow in Web Applications"),
                description: Some("A look at the flow of data in web applications and how it can be tamed for security."),
            }),
            date: datetime("2011-06-12T12:00:00-07:00"),
        },
        page! {
            handler: research::web_browser_javascript_cryptography,
            slug: "web-browser-javascript-cryptography",
            title: "Web Browser Cryptography is a Good Thing",
            description: "Arguments for and against doing cryptography in the browser.",
            keywords: "javascript cryptography, web browser cryptography, browser cryptography, encryption",
            legacy_hit_count_id: "pages/research/web-browser-javascript-cryptography.php",
            upvote: Some(UpvoteConfig {
                id: "webbrowsercryptography",
                category: "defuse_research",
                title: Some("Web Browser Cryptography is a Good Thing"),
                description: Some("Why we should support the development of browser-based crypto applications."),
            }),
            date: datetime("2013-01-23T12:00:00-07:00"),
            banner: Some("<div class=\"deprecated-banner\">Update: A modern approach to solving this problem would be to use <a href=\"https://web.dev/articles/signed-exchanges\">Signed Exchanges</a> or <a href=\"https://github.com/freedomofpress/webcat\">WEBCAT</a>.</div>"),
        },

        // ===== Miscellaneous =====
        page! {
            handler: misc::advice_to_aspiring_computer_engineers,
            slug: "advice-to-aspiring-computer-engineers",
            title: "Advice to Aspiring Computer Engineers and Scientists",
            description: "Advice for new computer science students.",
            keywords: "advice, computer science",
            legacy_hit_count_id: "pages/misc/advice-to-aspiring-computer-engineers.php",
            upvote: Some(UpvoteConfig {
                id: "advicetocs",
                category: "defuse_misc",
                title: Some("Advice to Aspiring Computer Security Engineers/Scientists"),
                description: Some("Some advice for new computer science students based on my experience."),
            }),
            date: datetime("2015-02-16T12:00:00-07:00"),
        },
        page! {
            handler: misc::centripetal_acceleration,
            slug: "centripetal-acceleration",
            title: "Centripetal Acceleration",
            description: "A derivation of the Centripetal Acceleration equation",
            keywords: "centripetal force, centripetal acceleration",
            legacy_hit_count_id: "pages/misc/centripetal-acceleration.php",
            upvote: Some(UpvoteConfig {
                id: "centripetalaccel",
                category: "defuse_misc",
                title: Some("Centripetal Acceleration"),
                description: Some("Deriving the centripetal acceleration equation."),
            }),
            date: datetime("2014-04-29T20:31:56-06:00"),
        },
        page! {
            handler: misc::contributors,
            slug: "contributors",
            title: "Contributors",
            description: "A list of people and organizations that have contributed to Defuse Security",
            keywords: "contribution, donation, thanks",
            legacy_hit_count_id: "pages/misc/contributors.php",
            upvote: Some(UpvoteConfig {
                id: "contributors",
                category: "defuse_misc",
                title: Some("Contributors"),
                description: Some("A list of people and organizations that have contributed to Defuse Security."),
            }),
        },
        page! {
            handler: misc::fractal_zoom,
            slug: "fractal-zoom",
            title: "Fractal Zoom",
            description: "A psychedelic short story.",
            keywords: "fractal zoom, short story, sci-fi, psychedelic",
            legacy_hit_count_id: "pages/misc/fractal-zoom.php",
            upvote: Some(UpvoteConfig {
                id: "fractalzoom",
                category: "defuse_misc",
                title: Some("Fractal Zoom"),
                description: Some("A psychedelic short story."),
            }),
            date: datetime("2024-11-15T12:00:00-07:00"),
        },
        page! {
            handler: misc::new_york_times_algebra,
            slug: "new-york-times-algebra",
            title: "Does the New York Times Fail at Algebra? (No.)",
            description: "The New York Times does not (necessarily) fail at algebra.",
            keywords: "new york times, the interview, algebra, sales",
            legacy_hit_count_id: "pages/misc/new-york-times-algebra.php",
            upvote: Some(UpvoteConfig {
                id: "newyorktimesalgebra",
                category: "defuse_misc",
                title: Some("The New York Times and Algebra"),
                description: Some("The New York Times does not (necessarily) fail at algebra."),
            }),
            date: datetime("2015-01-04T12:00:00-07:00"),
        },
        page! {
            handler: misc::pocorgtfo,
            slug: "pocorgtfo",
            title: "PoC || GTFO Mirror",
            description: "Mirror of all the Poc || GTFO issues.",
            keywords: "proof, of, concept, or, get, the, fuck, out",
            legacy_hit_count_id: "pages/misc/pocorgtfo.php",
            upvote: Some(UpvoteConfig {
                id: "pocorgtfo",
                category: "defuse_misc",
                title: Some("PoC || GTFO Mirror"),
                description: Some("Mirror of all the PoC || GTFO issues."),
            }),
        },
        // page! {
        //     handler: misc::rules_for_working_with_me,
        //     slug: "rules-for-working-with-me",
        //     title: "Rules For Working With Me",
        //     description: "How to get along with me.",
        //     keywords: "employment, working with me, teamwork",
        //     legacy_hit_count_id: "pages/misc/rules-for-working-with-me.php",
        //     upvote: None,
        // },
        page! {
            handler: misc::the_meaning_of_if,
            slug: "the-meaning-of-if",
            title: "The meaning of \"IF\" -- An Introduction to Formal Logic",
            description: "What the word \"If\" means in formal logic",
            keywords: "formal logic introduction, meaning of if, what if means",
            legacy_hit_count_id: "pages/misc/the-meaning-of-if.php",
            upvote: None,
            date: datetime("2013-03-30T20:56:53+00:00"),
        },
        page! {
            handler: misc::the_universe_is_made_of_cheese,
            slug: "the-universe-is-made-of-cheese",
            title: "The Universe is Made of Cheese - A Formal Proof",
            description: "A logical proof that the universe consists entirely of cheese.",
            keywords: "cheese paradox, universe made of cheese, logical proof",
            legacy_hit_count_id: "pages/misc/the-universe-is-made-of-cheese.php",
            upvote: Some(UpvoteConfig {
                id: "universeOfCheese",
                category: "defuse_misc",
                title: Some("The Cheese Universe Paradox"),
                description: Some("A formal proof that the universe is made entirely of cheese."),
            }),
            date: datetime("2013-03-11T20:50:04+00:00"),
        },
        page! {
            handler: misc::truecrypt_7_1a_hashes,
            slug: "truecrypt-7.1a-hashes",
            title: "TrueCrypt 7.1a Hashes",
            description: "SHA256 and SHA1 hashes of the last version of TrueCrypt.",
            keywords: "TrueCrypt, 7.1a, 7.1, SHA256, MD5, SHA1",
            legacy_hit_count_id: "pages/misc/truecrypt-7.1a-hashes.php",
            upvote: Some(UpvoteConfig {
                id: "truecrypthashes",
                category: "defuse_misc",
                title: Some("Hashes of TrueCrypt Version 7.1a Files"),
                description: Some("Hashes of all files from the last version of TrueCrypt"),
            }),
            date: datetime("2014-05-31T12:00:00-07:00"),
        },
        page! {
            handler: misc::x_plane_combat,
            slug: "x-plane-combat",
            title: "Combat in X-Plane: Weapon Setup, Enemy Aircraft, and Targeting",
            description: "How to fight in the X-Plane simulator.",
            keywords: "x-plane combat, fighter jet, flight simulator, weapon select, enemy aircraft",
            legacy_hit_count_id: "pages/misc/x-plane-combat.php",
            upvote: Some(UpvoteConfig {
                id: "xplanecombat",
                category: "defuse_misc",
                title: Some("Combat in X-Plane 10"),
                description: Some("How to configure X-Plane 10 for combat."),
            }),
            banner: Some("<div class=\"deprecated-banner\">This page is outdated.</div>"),
            date: datetime("2013-07-19T22:43:46-06:00"),
        },
        page! {
            handler: misc::claude_statusline,
            slug: "claude-statusline",
            title: "Claude Code Status Line",
            description: "A custom status line for Claude Code showing context usage, costs, and git branch.",
            keywords: "claude code, status line, statusline, cli",
            legacy_hit_count_id: "claude-statusline",
            upvote: Some(UpvoteConfig {
                id: "claudestatusline",
                category: "defuse_misc",
                title: Some("Claude Code Status Line"),
                description: Some("A custom status line for Claude Code showing context usage, costs, and git branch."),
            }),
            date: datetime("2026-02-22T15:13:51-07:00"),
        },

        // ===== Projects =====
        page! {
            handler: projects::bochs_images,
            slug: "bochs-images",
            title: "Disk Images for the Bochs x86 Emulator",
            description: "Various operating systems installed on disk images for Bochs.",
            keywords: "",
            legacy_hit_count_id: "pages/projects/bochs-images.php",
            upvote: Some(UpvoteConfig {
                id: "bochsdiskimages",
                category: "defuse_projects",
                title: Some("Bochs Disk Images"),
                description: Some("Disk images for the Bochs x86 emulator."),
            }),
            date: datetime("2013-12-06T12:00:00-07:00"),
            banner: Some(DEPRECATED_BANNER),
        },
        page! {
            handler: projects::email_spoofing_in_ruby,
            slug: "email-spoofing-in-ruby",
            title: "Spoofing SMTP email with a Ruby script - Defuse Security",
            description: "Example script for communicating with an SMTP server in Ruby to send spoofed email.",
            keywords: "email spoofing, smtp spoofing, ruby email, ruby smtp",
            legacy_hit_count_id: "pages/projects/email-spoofing-in-ruby.php",
            upvote: Some(UpvoteConfig {
                id: "email_spoofing_ruby",
                category: "defuse_projects",
                title: Some("Email Spoofing in Ruby"),
                description: Some("A Ruby script for spoofing email to SMTP servers."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2012-10-30T22:40:44+00:00"),
        },
        page! {
            handler: projects::force_print_background,
            slug: "force-print-background",
            title: "HTML/CSS Force Printing of Background Color - Defuse Security",
            description: "HTML/CSS Hack to get browsers to print background colors.",
            keywords: "print background color, html, css, force print background color, print stylesheet",
            legacy_hit_count_id: "pages/projects/force-print-background.php",
            upvote: Some(UpvoteConfig {
                id: "forceprinthtmlbg",
                category: "defuse_projects",
                title: Some("Forcing HTML/CSS Background Color to Print"),
                description: Some("How to force browsers to print the background color of HTML elements (using images)."),
            }),
            date: datetime("2011-11-04T23:05:19+00:00"),
        },
        page! {
            handler: projects::generating_random_passwords,
            slug: "generating-random-passwords",
            title: "Generating Unbiased Random Passwords in PHP",
            description: "Code for generating SECURE random passwords in PHP.",
            keywords: "generating passwords with php, generating passwords, php, random passwords",
            legacy_hit_count_id: "pages/projects/generating-random-passwords.php",
            upvote: Some(UpvoteConfig {
                id: "generatingrandompasswords",
                category: "defuse_projects",
                title: Some("Generating Random Passwords in PHP"),
                description: Some("How to generate unbiased passwords in PHP (plus some common mistakes)."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2012-02-29T22:53:11+00:00"),
        },
        page! {
            handler: projects::gnutls_psk_client_server_example,
            slug: "gnutls-psk-client-server-example",
            title: "GnuTLS Pre-Shared Key (PSK) Client-Server Example Code",
            description: "How to establish an SSL/TLS connection with GnuTLS and PSK authentication.",
            keywords: "gnutls, ssl, tls, https, client, server, psk, authentication",
            legacy_hit_count_id: "pages/projects/gnutls-psk-client-server-example.php",
            upvote: Some(UpvoteConfig {
                id: "gnutlspsk",
                category: "defuse_projects",
                title: Some("GnuTLS Pre-Shared Key Client-Server Example"),
                description: Some("How to establish an SSL/TLS connection with GnuTLS and PSK authentication."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2013-04-18T20:54:53+00:00"),
        },
        page! {
            handler: projects::online_free_computer_science_education,
            slug: "online-free-computer-science-education",
            title: "Computer Science Video Lecture Collection",
            description: "A collection of computer science related videos from various universities.",
            keywords: "computer science lecture, programming lecture, education, free education",
            legacy_hit_count_id: "pages/projects/online-free-computer-science-education.php",
            upvote: Some(UpvoteConfig {
                id: "onlinefreecseducation",
                category: "defuse_misc",
                title: Some("Computer Science Video Lecture Collection"),
                description: Some("A collection of computer science related videos from various universities."),
            }),
            date: datetime("2013-02-09T02:21:25+00:00"),
        },
        page! {
            handler: projects::php_hit_counter,
            slug: "php-hit-counter",
            title: "PHP & MySQL Unique Hit Count Tracker - Defuse Security",
            description: "A unique hit counter for PHP. Tracks unique hits without storing the IP address.",
            keywords: "hit counter, php, secure, private, anonymous, unique hits, track",
            legacy_hit_count_id: "pages/projects/php-hit-counter.html",
            upvote: Some(UpvoteConfig {
                id: "phphitcounter",
                category: "defuse_projects",
                title: Some("\"Privacy Aware\" Unique Hit Counter for PHP"),
                description: Some("A simple hit counter that stores only a hash of your visitor's IP address."),
            }),
            banner: Some(DEPRECATED_BANNER),
        },
        page! {
            handler: projects::php_pbkdf2,
            slug: "php-pbkdf2",
            title: "PBKDF2 Password Hashing for PHP",
            description: "Standards compliant PBKDF2 implementation for PHP.",
            keywords: "pbkdf2 for php, key derivation, password hashing",
            legacy_hit_count_id: "pages/projects/php-pbkdf2.php",
            upvote: Some(UpvoteConfig {
                id: "phppbkdf2",
                category: "defuse_projects",
                title: Some("PBKDF2 for PHP"),
                description: Some("A fast implementation of the PBKDF2 key stretching function in PHP."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2011-09-06T16:23:32+00:00"),
        },
        page! {
            handler: projects::projects,
            slug: "projects",
            title: "Defuse Security's Projects",
            description: "All of Defuse Security's projects.",
            keywords: "security, computer security, projects",
            legacy_hit_count_id: "pages/projects/projects.html",
            upvote: None,
        },
        page! {
            handler: projects::secure_php_encryption,
            slug: "secure-php-encryption",
            title: "Encrypting Data in PHP (HowTo) - Defuse Security",
            description: "Source code for encrypting data in PHP with mcrypt. The right way to do it.",
            keywords: "php encrypiton, php aes, encryption in php, php decryption",
            legacy_hit_count_id: "pages/projects/secure-php-encryption.php",
            upvote: Some(UpvoteConfig {
                id: "securephpencryption",
                category: "defuse_projects",
                title: Some("How to Encrypt Data in PHP"),
                description: Some("The right way to encrypt data in PHP."),
            }),
            banner: Some("<div class=\"deprecated-banner\">While the PHP encryption library linked below is still maintained, you probably want to use <a href=\"https://github.com/paragonie/halite\">Halite</a> instead.</div>"),
            date: datetime("2012-11-14T02:40:15+00:00"),
        },
        page! {
            handler: projects::syntax_highlighting_in_php_with_vim,
            slug: "syntax-highlighting-in-php-with-vim",
            title: "Scripting Vim's HTML syntax highlighting in PHP",
            description: "Using the Vim editor to highlight code syntax from PHP",
            keywords: "",
            legacy_hit_count_id: "pages/projects/syntax-highlighting-in-php-with-vim.php",
            upvote: Some(UpvoteConfig {
                id: "syntaxhighlightingvim",
                category: "defuse_projects",
                title: Some("Using the Vim Editor for Syntax Highlighting in PHP"),
                description: Some("Generate syntax-highlighted code automatically in PHP with Vim."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2012-08-24T06:01:06+00:00"),
        },
        page! {
            handler: projects::web_browser_negative_feedback,
            slug: "web-browser-negative-feedback",
            title: "Negative Feedback for Insecure Connections",
            description: "Should web browser interfaces provide negative feedback when the connection is insecure?",
            keywords: "negative feedback, insecure connections, http, https, ssl, tls, ev",
            legacy_hit_count_id: "pages/projects/web-browser-negative-feedback.php",
            upvote: Some(UpvoteConfig {
                id: "webbrowsernegativefeedback",
                category: "defuse_research",
                title: Some("Negative Feedback for Insecure Connections"),
                description: Some("Should web browser interfaces provide negative feedback when the connection is insecure?"),
            }),
            banner: Some("<div class=\"deprecated-banner\">This article is outdated.</div>"),
            date: datetime("2014-03-06T13:04:19-07:00"),
        },
        page! {
            handler: projects::dawr,
            slug: "dawr",
            title: "DAWr - Audio Playground for Rust",
            description: "A simple DAW library for Rust with a wavetable synthesizer, sampler, and audio effects.",
            keywords: "daw, rust, audio, synthesizer, wavetable, sampler",
            legacy_hit_count_id: "dawr",
            upvote: Some(UpvoteConfig {
                id: "dawr",
                category: "defuse_projects",
                title: Some("DAWr - Audio Playground for Rust"),
                description: Some("A simple DAW library for Rust with a wavetable synthesizer, sampler, and audio effects."),
            }),
        },
        page! {
            handler: projects::wavetool,
            slug: "wavetool",
            title: "wavetool - Serum Wavetable Processor",
            description: "A command-line tool for processing and analyzing Serum wavetables, with spectrogram generation and harmonic filtering.",
            keywords: "wavetable, serum, spectrogram, harmonics, sound design",
            legacy_hit_count_id: "wavetool",
            upvote: Some(UpvoteConfig {
                id: "wavetool",
                category: "defuse_projects",
                title: Some("wavetool - Serum Wavetable Processor"),
                description: Some("A command-line tool for processing and analyzing Serum wavetables."),
            }),
        },

        // ===== Software =====
        page! {
            handler: software::backup_verify_script,
            slug: "backup-verify-script",
            title: "Script for Comparing Folders and Validating Backups",
            description: "A command-line script for verifying backups by comparing two folders in Linux",
            keywords: "backup validate, backup verify, compare folders, linux, ruby",
            legacy_hit_count_id: "pages/software/backup-verify-script.php",
            upvote: Some(UpvoteConfig {
                id: "backupverifyscript",
                category: "defuse_software",
                title: Some("Backup Verifier Script (Ruby)"),
                description: Some("A Ruby script that compares two directories and reports the differences."),
            }),
            banner: Some("<div class=\"deprecated-banner\">This page has been deprecated. The code/information below may no longer be maintained.<br />There&#039;s a new, better version of this tool: <a href=\"/vfy-backup-tester.htm\"><span class=\"monowb\">$ vfy</span> Directory Comparison Tool</a>.</div>"),
            date: datetime("2012-07-29T00:45:14+00:00"),
        },
        page! {
            handler: software::vfy_backup_tester,
            slug: "vfy-backup-tester",
            title: "`vfy` Directory Comparer",
            description: "A directory comparison tool for checking if backups have been completed or restored successfully.",
            keywords: "backup verify, directory comparison, blake3, backup tester, vfy",
            legacy_hit_count_id: "vfy-backup-tester",
            upvote: Some(UpvoteConfig {
                id: "vfybackuptester",
                category: "defuse_software",
                title: Some("`vfy` Directory Comparer"),
                description: Some("A directory comparison tool for checking if backups have been completed or restored successfully."),
            }),
            date: datetime("2026-02-07T12:00:00-07:00"),
        },
        page! {
            handler: software::helloworld_cms,
            slug: "helloworld-cms",
            title: "Secure and Light CMS for PHP - Defuse Security",
            description: "A lightweight, ultra-secure CMS for PHP",
            keywords: "secure cms, php cms, light cms, small cms, tiny cms, cms",
            legacy_hit_count_id: "pages/software/helloworld-cms.html",
            upvote: Some(UpvoteConfig {
                id: "helloworld",
                category: "defuse_software",
                title: Some("HelloWorld! - A Light & Secure CDS for PHP"),
                description: Some("A lightweight, ultra-secure, CMS/CDS for PHP"),
            }),
            banner: Some(DEPRECATED_BANNER),
        },
        page! {
            handler: software::software,
            slug: "software",
            title: "Defuse Security's Software",
            description: "Software created by Defuse Security",
            keywords: "",
            legacy_hit_count_id: "pages/software/software.html",
            upvote: None,
        },
        page! {
            handler: software::php_hash_cracker,
            slug: "php-hash-cracker",
            title: "Salted Hash Cracking PHP Script - Defuse Security",
            description: "Dictionary hash cracking PHP scripts (supports LOTS of hash types!!)",
            keywords: "hash cracking, dictionary attack, php hash cracking script",
            legacy_hit_count_id: "pages/software/php-hash-cracker.php",
            upvote: Some(UpvoteConfig {
                id: "phphashcracker",
                category: "defuse_software",
                title: Some("Salted Hash Cracking PHP Script"),
                description: Some("A script for cracking hashes when all you have is PHP."),
            }),
            banner: Some(DEPRECATED_BANNER),
            date: datetime("2012-04-03T00:59:19+00:00"),
        },
        page! {
            handler: software::sockstress,
            slug: "sockstress",
            title: "Sockstress Denial of Service Tool & Source Code - Defuse Security",
            description: "A C implementation of the sockstress attack from 2008.",
            keywords: "sockstress, source code, denial of service, proof of concept, dos, ddos",
            legacy_hit_count_id: "pages/software/sockstress.php",
            upvote: Some(UpvoteConfig {
                id: "sockstress",
                category: "defuse_software",
                title: Some("Sockstress DoS Tool"),
                description: Some("A public domain C implementation of the sockstress DoS attack."),
            }),
            date: datetime("2012-04-15T06:28:33+00:00"),
        },
        page! {
            handler: software::passgen,
            slug: "passgen",
            title: "Secure Windows & Linux Password Generator - Defuse Security",
            description: "A secure random password generator for Windows,  Linux and Macintosh. Generates ASCII and HEX.",
            keywords: "password generator, secure, encryption, windows, linux, macintosh",
            legacy_hit_count_id: "pages/software/passgen.html",
            upvote: Some(UpvoteConfig {
                id: "passgen",
                category: "defuse_software",
                title: Some("High-Security Offline Password Generator"),
                description: Some("A secure random password generator for Windows, Linux, and Mac."),
            }),
            no_cache: true,
        },
        alias!("passwords" => "passgen"),
        alias!("password" => "passgen"),
        alias!("pass" => "passgen"),
        page! {
            handler: software::crackstation_hashdb,
            slug: "crackstation-hashdb",
            title: "CrackStation's Hash Cracking Utility",
            description: "The indexing and lookup code behind CrackStation.net's hash cracking service.",
            keywords: "crackstation, hash cracking, lookup table, rainbow table, password cracking",
            legacy_hit_count_id: "crackstation-hashdb",
            upvote: Some(UpvoteConfig {
                id: "crackstationhashdb",
                category: "defuse_software",
                title: Some("CrackStation's Hash Cracking Utility"),
                description: Some("The indexing and lookup code behind CrackStation.net's hash cracking service."),
            }),
        },

        // ===== Audits =====
        page! {
            handler: audits::encfs,
            slug: "audits/encfs",
            title: "EncFS Security Audit",
            description: "Security audit of the EncFS encrypted filesystem.",
            keywords: "encfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/encfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditencfs",
                category: "defuse_research",
                title: Some("EncFS Security Audit"),
                description: Some("The results of an EncFS security audit."),
            }),
            date: datetime("2014-01-15T12:00:00-07:00"),
        },
        page! {
            handler: audits::encfs_old,
            slug: "audits/encfs-old",
            title: "EncFS Security Audit",
            description: "Security audit of the EncFS encrypted filesystem.",
            keywords: "encfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/encfs-old.php",
            upvote: None,
            date: datetime("2014-01-15T12:00:00-07:00"),
        },
        page! {
            handler: audits::ecryptfs,
            slug: "audits/ecryptfs",
            title: "eCryptfs Security Audit",
            description: "Security audit of the eCryptfs encrypted filesystem.",
            keywords: "eCryptfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/ecryptfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditecryptfs",
                category: "defuse_research",
                title: Some("eCryptfs Security Audit"),
                description: Some("The results of an eCryptfs security audit."),
            }),
            date: datetime("2014-01-22T12:00:00-07:00"),
        },
        page! {
            handler: audits::pefs,
            slug: "audits/pefs",
            title: "PEFS Security Audit",
            description: "Security audit of the PEFS encrypted filesystem.",
            keywords: "PEFS, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/pefs.php",
            upvote: Some(UpvoteConfig {
                id: "auditpefs",
                category: "defuse_research",
                title: Some("PEFS Security Audit"),
                description: Some("Security audit of the Private Encrypted File System (PEFS)."),
            }),
            date: datetime("2014-02-14T12:00:00-07:00"),
        },
        page! {
            handler: audits::zerobin,
            slug: "audits/zerobin",
            title: "ZeroBin Security Audit",
            description: "Security audit of the ZeroBin Zero-Knowledge Pastebin",
            keywords: "secure pastebin, security audit, zerobin",
            legacy_hit_count_id: "pages/audits/zerobin.php",
            upvote: Some(UpvoteConfig {
                id: "auditzerobin",
                category: "defuse_research",
                title: Some("ZeroBin Security Audit"),
                description: Some("A security audit of the ZeroBin pastebin."),
            }),
            date: datetime("2014-02-02T12:00:00-07:00"),
        },
        page! {
            handler: audits::gocryptfs,
            slug: "audits/gocryptfs",
            title: "Gocryptfs Security Audit",
            description: "Security audit of the gocryptfs encrypted filesystem",
            keywords: "gocryptfs, encrypted filesystem, security audit ",
            legacy_hit_count_id: "pages/audits/gocryptfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditgocryptfs0",
                category: "defuse_research",
                title: Some("Gocryptfs Security Audit"),
                description: Some("A security audit of the gocryptfs encrypted filesystem."),
            }),
            date: datetime("2017-03-03T12:00:00-07:00"),
        },
        page! {
            handler: audits::hash0,
            slug: "audits/hash0",
            title: "Hash0 Security Audit",
            description: "Security audit of the Hash0 password system",
            keywords: "hash0, security audit, cryptography, passwords",
            legacy_hit_count_id: "pages/audits/hash0.php",
            upvote: Some(UpvoteConfig {
                id: "audithashzero",
                category: "defuse_research",
                title: Some("Hash0 Security Audit"),
                description: Some("A security audit of the Hash0 pastebin."),
            }),
            date: datetime("2014-04-13T12:00:00-07:00"),
        },

        // ===== ZecSec posts =====
        // Landing page (consolidated overview, audits, contact)
        page! {
            handler: zecsec::index,
            slug: "zecsec",
            title: "ZecSec - Zcash Ecosystem Security",
            description: "Zcash ecosystem security research, audits, and vulnerability disclosures by the ZecSec project.",
            keywords: "zcash, security, audit, zecsec, cryptocurrency",
            legacy_hit_count_id: "zecsec",
            upvote: Some(UpvoteConfig {
                id: "zecsec",
                category: "zecsec",
                title: None,
                description: None,
            }),
        },
        // Posts (chronological by date)
        page! {
            handler: zecsec::october_update,
            slug: "zecsec/october-update",
            title: "October Update: Ywallet audited, and what's next? - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/october-update",
            upvote: Some(UpvoteConfig {
                id: "zecsecoctoberupdate",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2022-10-28T08:13:14-07:00"),
        },
        page! {
            handler: zecsec::scalable_private_money_needs_scalable_private_messaging,
            slug: "zecsec/scalable-private-money-needs-scalable-private-messaging",
            title: "Scalable Private Money Needs Scalable Anonymous Messaging - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/scalable-private-money-needs-scalable-private-messaging",
            upvote: Some(UpvoteConfig {
                id: "zecsecscalableprivatemoney",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2022-11-15T19:00:00-07:00"),
        },
        page! {
            handler: zecsec::security_audit_process,
            slug: "zecsec/security-audit-process",
            title: "Security Audit Process - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/security-audit-process",
            upvote: Some(UpvoteConfig {
                id: "zecsecsecurityauditprocess",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2022-12-29T07:00:00-07:00"),
        },
        page! {
            handler: zecsec::ywallet_audit_published,
            slug: "zecsec/ywallet-audit-published",
            title: "YWallet Audit Results Published - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/ywallet-audit-published",
            upvote: Some(UpvoteConfig {
                id: "zecsecywalletaudit",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-01-03T07:00:00-07:00"),
        },
        page! {
            handler: zecsec::zecsec_roadmap_for_2023,
            slug: "zecsec/zecsec-roadmap-for-2023",
            title: "ZecSec Roadmap for 2023 - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/zecsec-roadmap-for-2023",
            upvote: Some(UpvoteConfig {
                id: "zecsecroadmap2023",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-01-03T11:08:00-07:00"),
        },
        page! {
            handler: zecsec::transparency_report_2022_q4,
            slug: "zecsec/2022-q4-transparency-report",
            title: "ZecSec's Q4 2022 Transparency Report - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/2022-q4-transparency-report",
            upvote: Some(UpvoteConfig {
                id: "zecsecq42022report",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-01-27T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::making_zcash_light_wallets_faster_and_more_private,
            slug: "zecsec/making-zcash-light-wallets-faster-and-more-private",
            title: "Making Zcash Light Wallets Faster and More Private - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/making-zcash-light-wallets-faster-and-more-private",
            upvote: Some(UpvoteConfig {
                id: "zecseclightwallets",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-03-02T01:00:00-07:00"),
            math: true,
        },
        page! {
            handler: zecsec::risk_analysis_of_intel_sgx_and_other_tees,
            slug: "zecsec/risk-analysis-of-intel-sgx-and-other-tees",
            title: "Risk Analysis of Intel's SGX and Other TEEs - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/risk-analysis-of-intel-sgx-and-other-tees",
            upvote: Some(UpvoteConfig {
                id: "zecsecsgxtees",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-03-10T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::threat_model_for_zcash_hardware_wallets,
            slug: "zecsec/threat-model-for-zcash-hardware-wallets",
            title: "A Simple Threat Model for Zcash Shielded Hardware Wallets - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/threat-model-for-zcash-hardware-wallets",
            upvote: Some(UpvoteConfig {
                id: "zecsecthreatmodelhw",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-04-15T00:00:00-07:00"),
        },
        page! {
            handler: zecsec::transparency_report_2023_q1,
            slug: "zecsec/2023-q1-transparency-report",
            title: "ZecSec's Q1 2023 Transparency Report - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/2023-q1-transparency-report",
            upvote: Some(UpvoteConfig {
                id: "zecsecq12023report",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-04-18T01:00:00-07:00"),
        },
        alias!("zecsec/security-engineering" => "security-engineering-learning-from-safety-critical-disciplines"),
        alias!("zecsec/deep-dive-into-sgx-attacks" => "zecsec/risk-analysis-of-intel-sgx-and-other-tees"),
        page! {
            handler: zecsec::milk_sad,
            slug: "zecsec/milk-sad",
            title: "If you used libbitcoin-explorer (bx) to generate your seed phrase, rotate it ASAP! - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/milk-sad",
            upvote: Some(UpvoteConfig {
                id: "zecsecmilksad",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-08-11T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::free2z_security_audit,
            slug: "zecsec/free2z-security-audit",
            title: "Free2Z Security Audit Results - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/free2z-security-audit",
            upvote: Some(UpvoteConfig {
                id: "zecsecfree2zaudit",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-09-14T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::zcash_51_percent_attack,
            slug: "zecsec/zcash-51-percent-attack",
            title: "Mitigating 51% Attack Risk on the Zcash Network - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/zcash-51-percent-attack",
            upvote: Some(UpvoteConfig {
                id: "zecsec51percentattack",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-09-21T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::security_audit_of_hanhs_ledger_app,
            slug: "zecsec/security-audit-of-hanhs-ledger-app",
            title: "Results of Auditing Hanh's Shielded Zcash Ledger App - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/security-audit-of-hanhs-ledger-app",
            upvote: Some(UpvoteConfig {
                id: "zecsecledgerappaudit",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-09-21T01:01:00-07:00"),
        },
        page! {
            handler: zecsec::zecwallet_lite_cli_security_audit,
            slug: "zecsec/zecwallet-lite-cli-security-audit",
            title: "Security Audit of zecwallet-lite-cli - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/zecwallet-lite-cli-security-audit",
            upvote: Some(UpvoteConfig {
                id: "zecseczecwalletaudit",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-09-23T01:01:00-07:00"),
        },
        page! {
            handler: zecsec::future_of_zcash_ecosystem_security,
            slug: "zecsec/future-of-zcash-ecosystem-security",
            title: "The Future of Zcash Ecosystem Security - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/future-of-zcash-ecosystem-security",
            upvote: Some(UpvoteConfig {
                id: "zecsecfutureofsecurity",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2023-09-24T01:00:00-07:00"),
        },
        page! {
            handler: zecsec::zgo_security_audit,
            slug: "zecsec/zgo-security-audit",
            title: "ZGo Security Audit Results - ZecSec",
            description: "",
            keywords: "",
            legacy_hit_count_id: "zecsec/zgo-security-audit",
            upvote: Some(UpvoteConfig {
                id: "zecseczgoaudit",
                category: "zecsec",
                title: None,
                description: None,
            }),
            date: datetime("2024-01-05T00:00:00-07:00"),
        },

        // ===== Test pages =====
        page! {
            handler: panic_test,
            slug: "panic-test",
            title: "Panic Test",
            description: "Test page that panics during rendering.",
            keywords: "",
            legacy_hit_count_id: "panic-test",
            upvote: None,
        },
        page! {
            handler: test_directory,
            slug: "test-directory/",
            title: "Test Directory",
            description: "Test page for directory-style URL handling.",
            keywords: "",
            legacy_hit_count_id: "test-directory",
            upvote: None,
        },
    ];

    // Validate upvote IDs are valid CSS class names (they're used in class attributes in templates)
    for p in pages {
        if let Some(upvote) = &p.upvote {
            assert!(
                is_valid_css_class(upvote.id),
                "Upvote ID '{}' for page '{}' is not a valid CSS class name",
                upvote.id, p.slug
            );
        }
    }

    // Make sure hit count IDs get set for new pages.
    // TODO: Make it an option and automatically use the slug if it's None.
    pages.iter().for_each(|p| assert!(!p.legacy_hit_count_id.is_empty() || p.redirect.is_some()));

    // TODO: make it a loud error if there are entries with colliding lowercased slugs

    // Key on the lowercased slug for case-insensitive matching.
    // The proper-case version of the slug is still used for generating canonical URLs.
    pages
        .iter()
        .map(|p| (p.slug.to_lowercase().leak() as &'static str, p.clone()))
        .collect()
});

/// Check if a string is a valid CSS class name.
/// Must start with a letter, underscore, or hyphen, then only letters, digits, underscores, or hyphens.
fn is_valid_css_class(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    let mut chars = s.chars();
    let first = chars.next().unwrap();
    // This is stricter than CSS, since CSS allows e.g. "-abc" but not "-12a"
    if !first.is_ascii_alphabetic() {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}
