//! Page definitions for the registry.
//!
//! This file contains all page entries for PAGE_REGISTRY.
//! Edit this file to add, remove, or modify pages.

use std::collections::HashMap;
use std::sync::LazyLock;

use super::{alias, page, PageInfo, UpvoteConfig};

/// The page registry - all pages on the site
///
/// Keys are LOWERCASE for case-insensitive lookup.
/// The `slug` field in PageInfo stores the canonical case for URLs.
/// Empty string "" is the home page.
pub static PAGE_REGISTRY: LazyLock<HashMap<&'static str, PageInfo>> = LazyLock::new(|| {
    let pages: &[PageInfo] = &[
        // ===== Home page =====
        page! {
            handler: home,
            slug: "",
            title: "",
            description: "",
            keywords: "",
            legacy_hit_count_id: "pages/home.html",
            upvote: None,
        },

        // ===== Home page aliases =====
        alias!("index" => ""),
        alias!("index.html" => ""),
        alias!("index.php" => ""),

        // ===== Main pages =====
        page! {
            handler: about,
            slug: "about",
            title: "",
            description: "About Defuse Security.",
            keywords: "",
            legacy_hit_count_id: "pages/about.html",
            upvote: None,
        },
        page! {
            handler: contact,
            slug: "contact",
            title: "Defuse Security's Contact Information",
            description: "Defuse Security's contact information.",
            keywords: "",
            legacy_hit_count_id: "pages/contact.html",
            upvote: None,
        },
        alias!("key" => "contact"),
        page! {
            handler: donated,
            slug: "donated",
            title: "",
            description: "",
            keywords: "",
            legacy_hit_count_id: "pages/donated.html",
            upvote: None,
        },
        page! {
            handler: security_contact_vulnerability_disclosure,
            slug: "security-contact-vulnerability-disclosure",
            title: "Security Contact and Vulnerability Disclosure",
            description: "How to disclose vulnerabilities in Defuse Security services",
            keywords: "full disclosure, security contact, vulnerabilities",
            legacy_hit_count_id: "pages/security-contact-vulnerability-disclosure.php",
            upvote: None,
        },
        page! {
            handler: privacy_policy,
            slug: "privacy-policy",
            title: "",
            description: "",
            keywords: "",
            legacy_hit_count_id: "pages/privacy.html",
            upvote: None,
        },
        page! {
            handler: transparency,
            slug: "transparency",
            title: "Transparency Report",
            description: "",
            keywords: "",
            legacy_hit_count_id: "pages/transparency.php",
            upvote: None,
        },
        page! {
            handler: vimrc,
            slug: "vimrc",
            title: "My .vimrc - Defuse Security",
            description: "My Vim configuration file",
            keywords: "vim, vimrc, vim configuration",
            legacy_hit_count_id: "pages/vimrc.php",
            upvote: Some(UpvoteConfig {
                id: "myvimrc",
                category: "defuse_pages",
                title: Some("My Vim Configuration"),
                description: Some("My configuration of the Vim text and code editor."),
            }),
        },
        page! {
            handler: jobs,
            slug: "jobs",
            title: "Jobs",
            description: "Small jobs that you can do.",
            keywords: "small jobs",
            legacy_hit_count_id: "pages/jobs.php",
            upvote: None,
        },
        page! {
            handler: honestyware,
            slug: "honestyware",
            title: "Honestyware - The right way to sell software.",
            description: "Honestyware is a revolutionary way to sell software that embraces piracy.",
            keywords: "honestyware, free software, trust user",
            legacy_hit_count_id: "pages/honestyware.php",
            upvote: Some(UpvoteConfig {
                id: "honestyware",
                category: "defuse_pages",
                title: Some("Honestyware"),
                description: Some("A philosophy for selling software and other digital content on the internet."),
            }),
        },
        page! {
            handler: reading_list,
            slug: "reading-list",
            title: "Reading List - Defuse Security",
            description: "Everything I have read so far.",
            keywords: "reading list, infosec",
            legacy_hit_count_id: "pages/reading-list.php",
            upvote: Some(UpvoteConfig {
                id: "reading_list",
                category: "defuse_pages",
                title: Some("Reading List"),
                description: Some("A list of the books I have read."),
            }),
        },
        page! {
            handler: pdftribute,
            slug: "pdftribute",
            title: "#pdftribute",
            description: "#pdftribute",
            keywords: "#pdftribute",
            legacy_hit_count_id: "pages/pdftribute.php",
            upvote: None,
        },
        page! {
            handler: scratch,
            slug: "scratch",
            title: "",
            description: "",
            keywords: "",
            legacy_hit_count_id: "pages/scratch.html",
            upvote: None,
        },

        // ===== Services =====
        page! {
            handler: services::services,
            slug: "services",
            title: "Defuse Security's Services",
            description: "Defuse Security's Services.",
            keywords: "",
            legacy_hit_count_id: "pages/services/services.html",
            upvote: None,
        },
        page! {
            handler: services::checksums,
            slug: "checksums",
            title: "Online Text and File Hash Calculator - MD5, SHA1, SHA256, SHA512, WHIRLPOOL Hash Calculator - Defuse Security",
            description: "Online Hash Tool. Calculate hash of file or text. MD5, SHA1, SHA256, SHA512 and more...",
            keywords: "file hasher, online, hash, md5, sha256, sha1, text hash, checksum",
            legacy_hit_count_id: "pages/services/checksums.php",
            upvote: Some(UpvoteConfig {
                id: "onlinechecksums",
                category: "defuse_pages",
                title: Some("Online Hash Calculator"),
                description: Some("A tool for computing hashes (MD5, SHA1, SHA2, etc.) of text and files."),
            }),
        },
        page! {
            handler: services::software_security_auditing,
            slug: "software-security-auditing",
            title: "Software Security Auditing",
            description: "Get your software audited for security bugs.",
            keywords: "software security, exploits, auditing",
            legacy_hit_count_id: "pages/services/software-security-auditing.php",
            upvote: None,
        },
        page! {
            handler: services::softwaredevelopment,
            slug: "softwaredevelopment",
            title: "Custom Software Development - Defuse Security",
            description: "Custom secure software development to suit your needs.",
            keywords: "software development, custom software, programming, security",
            legacy_hit_count_id: "pages/services/softwaredevelopment.html",
            upvote: None,
        },
        page! {
            handler: services::webdevelopment,
            slug: "webdevelopment",
            title: "Custom Web Design and Development - Defuse Security",
            description: "Custom web software development.",
            keywords: "",
            legacy_hit_count_id: "pages/services/webdevelopment.html",
            upvote: None,
        },
        page! {
            handler: services::web_server_scan,
            slug: "web-server-scan",
            title: "Web Server Security Scan - Defuse Security",
            description: "Test your web server for common configuration problems such as open relay, zone transfer, and much more.",
            keywords: "security scan, web server scan, zone transfer test, open relay test",
            legacy_hit_count_id: "pages/services/scan.php",
            upvote: None,
        },

        // ===== Research =====
        page! {
            handler: research::asuskeyboarddefect,
            slug: "asuskeyboarddefect",
            title: "ASUS G50 G51 Keyboard Problem: Backspace, P, and 1 keys don't work. - Defuse Security",
            description: "Solution to the keyboard problem for the ASUS G50, G51, and G51VX series laptops.",
            keywords: "asus keyboard, g series, g51, g50, g51vx, backspace, p, q, keys, broken",
            legacy_hit_count_id: "pages/research/asuskeyboarddefect.html",
            upvote: Some(UpvoteConfig {
                id: "asuskeyboarddefect",
                category: "defuse_pages",
                title: Some("Asus G Series Keyboard Design Error"),
                description: Some("Fixing a problem with the keyboard in an ASUS laptop."),
            }),
        },
        alias!("keyboarddefect" => "asuskeyboarddefect"),
        page! {
            handler: research::bitcoin_pool_ddos,
            slug: "bitcoin-pool-ddos",
            title: "BitCoin Centralization - DDoS Attacks on Pools & Mt. Gox Hacked - Defuse Security",
            description: "Centralization is harmful to the BitCoin network and community.",
            keywords: "bitcoin, ddos, denial of service, pool, mining, mtgox, centralization, hacked",
            legacy_hit_count_id: "pages/research/bitcoin-pool-ddos.html",
            upvote: Some(UpvoteConfig {
                id: "bitcoinpoolddos",
                category: "defuse_pages",
                title: Some("Centralization is Killing Bitcoin"),
                description: Some("An article on Bitcoin, centralization, and DDoS attacks."),
            }),
        },
        page! {
            handler: research::blind_birthday_attack,
            slug: "blind-birthday-attack",
            title: "Blind Birthday Attack",
            description: "Birthday attack without seeing the values.",
            keywords: "birthday attack, blind, double hmac, cryptography",
            legacy_hit_count_id: "pages/research/blind-birthday-attack.php",
            upvote: Some(UpvoteConfig {
                id: "blindbirthdayattack",
                category: "defuse_pages",
                title: Some("Blind Birthday Attack"),
                description: Some("A birthday attack without knowing what the collision actually is."),
            }),
        },
        page! {
            handler: research::blockwise_factoring,
            slug: "blockwise-factoring",
            title: "Blockwise Factoring - An efficient and simple method for factoring small integers. ",
            description: "Blockwise Factoring is a method for factoring the product of two primes that uses only addition, subtraction, and comparison.",
            keywords: "",
            legacy_hit_count_id: "pages/research/blockwise-factoring.php",
            upvote: None,
        },
        page! {
            handler: research::bochs_hacking_guide,
            slug: "bochs-hacking-guide",
            title: "Bochs Hacking Guide",
            description: "Hacking the Bochs x86 CPU emulator. Changing and adding instructions.",
            keywords: "bochs, emulator, cpu, architecture, x86, intel, ia-32",
            legacy_hit_count_id: "pages/research/bochs-hacking-guide.php",
            upvote: Some(UpvoteConfig {
                id: "bochshacking",
                category: "defuse_pages",
                title: Some("Bochs Hacking Guide"),
                description: Some("Hacking the Bochs x86 CPU emulator."),
            }),
        },
        page! {
            handler: research::cbcmodeiv,
            slug: "cbcmodeiv",
            title: "Should CBC Mode Initialization Vector Be Secret - Defuse Security",
            description: "Should the initialization vector used for CBC mode be kept secret?",
            keywords: "cbc mode, encryption, initialization vector, iv, secret, secure",
            legacy_hit_count_id: "pages/research/cbcmodeiv.php",
            upvote: Some(UpvoteConfig {
                id: "cbcmodeiv",
                category: "defuse_pages",
                title: Some("Encryption - CBC Mode IV: Secret or Not?"),
                description: Some("Should the IV in CBC mode be kept secret?"),
            }),
        },
        page! {
            handler: research::choosing_good_passwords_longer_is_better,
            slug: "choosing-good-passwords-longer-is-better",
            title: "How to Pick a Good Password - Longer is Better - Defuse Security",
            description: "The length of passwords is far more important than their character set or randomness.",
            keywords: "",
            legacy_hit_count_id: "pages/research/choosing-good-passwords-longer-is-better.html",
            upvote: None,
        },
        page! {
            handler: research::concentration_bounds_from_parallel_repetition_theorems,
            slug: "concentration-bounds-from-parallel-repetition-theorems",
            title: "Concentration Bounds from Parallel Repetition Theorems",
            description: "My master's thesis, showing how concentration bounds can be derived from parallel repetition theorems for nonlocal games and interactive proofs.",
            keywords: "concentration bounds, parallel repetition theorems, quantum information, symmetric key strengthening",
            legacy_hit_count_id: "pages/research/concentration-bounds-from-parallel-repetition-theorems.php",
            upvote: Some(UpvoteConfig {
                id: "mastersthesis",
                category: "defuse_pages",
                title: Some("Concentration Bounds from Parallel Repetition Theorems"),
                description: Some("My master's thesis, showing how concentration bounds can be derived from parallel repetition theorems for nonlocal games and interactive proofs."),
            }),
        },
        page! {
            handler: research::cracking_synergy_bad_cryptography,
            slug: "cracking-synergy-bad-cryptography",
            title: "Cracking Synergy's Bad Cryptography",
            description: "A tool to crack Synergy's homebrew cryptography",
            keywords: "synergy, cryptography, crack, homebrew, keyboard sharing, mouse sharing",
            legacy_hit_count_id: "pages/research/cracking-synergy-bad-cryptography.php",
            upvote: Some(UpvoteConfig {
                id: "synergy_cracking",
                category: "defuse_pages",
                title: Some("Cracking Synergy's Bad Cryptography"),
                description: Some("A tool to crack Synergy's homebrew cryptography."),
            }),
        },
        page! {
            handler: research::cryptographyunderattack,
            slug: "cryptographyunderattack",
            title: "Cryptography Under Attack - Defuse Security",
            description: "Cryptography under attack essay.",
            keywords: "",
            legacy_hit_count_id: "pages/research/cryptographyunderattack.html",
            upvote: None,
        },
        page! {
            handler: research::exploiting_cpp_vtables,
            slug: "exploiting-cpp-vtables",
            title: "Instance Replacement: Exploiting C++ VTABLES",
            description: "How C++ classes are represented, how VTABLES work, and how to exploit them.",
            keywords: "vtable overwriting, vtable exploit, buffer overflow, vulnerability",
            legacy_hit_count_id: "pages/research/exploiting-cpp-vtables.php",
            upvote: Some(UpvoteConfig {
                id: "cppvtables",
                category: "defuse_pages",
                title: Some("Exploiting C++ VTABLES: Instance Replacement"),
                description: Some("Use a memory corruption vulnerability to change an instance of class A into an instance of class B."),
            }),
        },
        page! {
            handler: research::in_browser_port_scanning,
            slug: "in-browser-port-scanning",
            title: "Port Scanning Local Network From a Web Browser",
            description: "Malicious web pages can port scan your local network.",
            keywords: "browser, port scan, security",
            legacy_hit_count_id: "pages/research/in-browser-port-scanning.php",
            upvote: Some(UpvoteConfig {
                id: "inbrowserportscanner",
                category: "defuse_pages",
                title: Some("Timing Side Channel Port Scanner in the Browser"),
                description: Some("How web pages can use a timing side channel to \"scan\" your local network."),
            }),
        },
        page! {
            handler: research::filesystem_events_ntfs_permissions,
            slug: "filesystem-events-ntfs-permissions",
            title: "File System Events Disclose NTFS Protected Folder Contents - Defuse Security",
            description: "Obtain list of files in folder protected with NTFS permissions via filesystem events",
            keywords: "",
            legacy_hit_count_id: "pages/research/filesystemevents.html",
            upvote: Some(UpvoteConfig {
                id: "filesystemevents",
                category: "defuse_pages",
                title: Some("File System Events Leak Folder Contents"),
                description: Some("An information disclosure vulnerability in Windows shared folders that lets you see what's in folers you can't access."),
            }),
        },
        page! {
            handler: research::godel_second_incompleteness_theorem_by_turing_machines,
            slug: "godel-second-incompleteness-theorem-by-turing-machines",
            title: "A Simple Proof of Gödel's Second Incompleteness Theorem Using Turing Machines",
            description: "Proving Gödel's second incompleteness theorem in a simpler way using Turing machines.",
            keywords: "godel, second incompleteness theorem, simple proof, turing machines, computability",
            legacy_hit_count_id: "pages/research/godel-second-incompleteness-theorem-by-turing-machines.php",
            upvote: Some(UpvoteConfig {
                id: "godelsecondtms",
                category: "defuse_pages",
                title: Some("A Simple Proof of Gödel's Second Incompleteness Theorem Using Turing Machines"),
                description: Some("Proving Gödel's second incompleteness theorem in a way that should be understandable to anyone who understands the proof that the halting problem is undecidable."),
            }),
        },
        page! {
            handler: research::grc_passwords_not_secure,
            slug: "grc-passwords-not-secure",
            title: "GRC's Perfect Password Generator is Not Cryptographically Secure",
            description: "Why GRC's Perfect Password Generator is not a CSPRNG",
            keywords: "grc perfect passwords, security of grc perfect passwords, csprng, cryptographically secure, state compromise extension",
            legacy_hit_count_id: "pages/research/grc-passwords-not-secure.php",
            upvote: None,
        },
        page! {
            handler: research::how_do_we_model_this_robot,
            slug: "how-do-we-model-this-robot",
            title: "How do we model this robot?",
            description: "Modeling Computational Ability and Informational Ability.",
            keywords: "langsec, robot, modeling, computational, informational",
            legacy_hit_count_id: "pages/research/how-do-we-model-this-robot.php",
            upvote: Some(UpvoteConfig {
                id: "howdowemodelthisrobot",
                category: "defuse_pages",
                title: Some("How do we model this robot?"),
                description: Some("The difference between Computational Ability and Informational Ability"),
            }),
        },
        page! {
            handler: research::instruction_filters,
            slug: "instruction-filters",
            title: "Instruction Filters as an Exploitation Defense",
            description: "Disabling CPU instructions to thwart ROP and other attacks.",
            keywords: "instruction set filters, insfilter, research",
            legacy_hit_count_id: "pages/research/instruction-filters.php",
            upvote: None,
        },
        page! {
            handler: research::internetdangers,
            slug: "internetdangers",
            title: "Dangers of the Internet - Defuse Security",
            description: "Dangers of the Internet, an explanation of the dangers you face online.",
            keywords: "",
            legacy_hit_count_id: "pages/research/internetdangers.html",
            upvote: None,
        },
        page! {
            handler: research::is_security_local,
            slug: "is-security-local",
            title: "Is Security Local?",
            description: "Is security a locally-verifiable property of computation?",
            keywords: "langsec, security, locality, verification",
            legacy_hit_count_id: "pages/research/is-security-local.php",
            upvote: Some(UpvoteConfig {
                id: "issecuritylocal",
                category: "defuse_pages",
                title: Some("Is Security Local?"),
                description: Some("Is security a locally-verifiable property of computation?"),
            }),
        },
        page! {
            handler: research::onedetection,
            slug: "onedetection",
            title: "The PUP Confusion Antivirus Detection Evasion Technique - Defuse Security",
            description: "The PUP Confusion Antivirus Detection Evasion Technique. Multiple detections per file.",
            keywords: "antivirus, single detection, only one detection, can't detect more than one, multiple virus, two viruses in one file",
            legacy_hit_count_id: "pages/research/onedetection.html",
            upvote: Some(UpvoteConfig {
                id: "pupconfusion",
                category: "defuse_pages",
                title: Some("The PUP Confusion Technique"),
                description: Some("Undetecting malware by making it look like a Potentially Unwanted Program (PUP)."),
            }),
        },
        page! {
            handler: research::password_hashing_after_phc,
            slug: "password-hashing-after-phc",
            title: "Password Hashing After PHC",
            description: "Giving authenticators an advantage over password crackers with cache.",
            keywords: "password hashing competition, key stretching, caching",
            legacy_hit_count_id: "pages/research/password-hashing-after-phc.php",
            upvote: Some(UpvoteConfig {
                id: "passhashingphc",
                category: "defuse_pages",
                title: Some("Password Hashing After the PHC"),
                description: Some("Giving authenticators an advantage over password crackers with cache."),
            }),
        },
        page! {
            handler: research::passwordinsecurity,
            slug: "passwordinsecurity",
            title: "Are Passwords Secure? - Defuse Security",
            description: "Finding out if passwords are right way to be authenticating users.",
            keywords: "",
            legacy_hit_count_id: "pages/research/passwordinsecurity.html",
            upvote: None,
        },
        page! {
            handler: research::plausible_reason_p_noteq_np_is_hard_to_prove,
            slug: "plausible-reason-p-noteq-np-is-hard-to-prove",
            title: "A Plausible Reason It's So Hard To Prove P!=NP",
            description: "Attempting to show why P!=NP is hard to prove using hash functions.",
            keywords: "p versus np, hard to prove, hash functions, language collisions",
            legacy_hit_count_id: "pages/research/plausible-reason-p-noteq-np-is-hard-to-prove.php",
            upvote: Some(UpvoteConfig {
                id: "plausiblepneqnpprove",
                category: "defuse_pages",
                title: Some("A Plausible Reason It's So Hard To Prove P!=NP"),
                description: Some("Attempting to show why P!=NP is hard to prove using hash functions."),
            }),
        },
        page! {
            handler: research::password_policy_statistics,
            slug: "password-policy-statistics",
            title: "Password Policy Statistics - Defuse Security",
            description: "Password length and character restriction statistics. Top 100 sites.",
            keywords: "password, statistics, restrictions, maximum length, symbols, plain text, hashing, salt",
            legacy_hit_count_id: "pages/research/password-policy-statistics.php",
            upvote: None,
        },
        page! {
            handler: research::password_policy_hall_of_shame,
            slug: "password-policy-hall-of-shame",
            title: "Password Policy Hall of SHAME - Defuse Security",
            description: "List of websites and services that impose password restrictions and may be storing passwords in plaintext.",
            keywords: "hall of shame, password hall of shame, plaintext, password restrictions, maximum password length, restriction, insecure",
            legacy_hit_count_id: "pages/research/hallofshame.php",
            upvote: Some(UpvoteConfig {
                id: "pphos",
                category: "defuse_pages",
                title: Some("Password Policy Hall of Shame"),
                description: Some("A list of web sites that store passwords in plain text, restrict password length, or restrict password characters"),
            }),
        },
        alias!("pphos" => "password-policy-hall-of-shame"),
        page! {
            handler: research::password_reset_key_escrow,
            slug: "password-reset-key-escrow",
            title: "Modernizing Password Reset & Key Escrow",
            description: "Why our password reset methods suck and how we can make them better.",
            keywords: "password reset security, key escrow, password recovery",
            legacy_hit_count_id: "pages/research/password-reset-key-escrow.php",
            upvote: None,
        },
        page! {
            handler: research::race_conditions_in_web_applications,
            slug: "race-conditions-in-web-applications",
            title: "Practical Race Condition (TOCTTOU) Vulnerabilities in Web Applications - Defuse Security",
            description: "Query-level race conditions can lead to serious but hard to find vulnerabilities in web applications.",
            keywords: "",
            legacy_hit_count_id: "pages/research/race-conditions-in-web-applications.php",
            upvote: Some(UpvoteConfig {
                id: "raceconditions",
                category: "defuse_pages",
                title: Some("Practical Race Condition Vulnerabilities in Web Applications"),
                description: Some("An example of a web application (PHP) vulnerable to a race condition, and how to fix it."),
            }),
        },
        page! {
            handler: research::research,
            slug: "research",
            title: "Defuse Security's Research",
            description: "Research projects by Defuse Security",
            keywords: "",
            legacy_hit_count_id: "pages/research/research.html",
            upvote: None,
        },
        page! {
            handler: research::side_channel_attacks_on_everyday_applications,
            slug: "side-channel-attacks-on-everyday-applications",
            title: "Side-Channel Attacks on Everyday Applications (Black Hat 2016)",
            description: "Data and code for my paper applying FLUSH+RELOAD to break privacy.",
            keywords: "cache side channel, experiment data, flush, reload, privacy",
            legacy_hit_count_id: "pages/research/side-channel-attacks-on-everyday-applications.php",
            upvote: Some(UpvoteConfig {
                id: "side-channel-attacks-on-everyday-applications",
                category: "defuse_pages",
                title: Some("Side-Channel Attacks on Everyday Applications"),
                description: Some("My Black Hat USA 2016 talk about the Flush+Reload side channel."),
            }),
        },
        alias!("bh2016" => "side-channel-attacks-on-everyday-applications"),
        alias!("BH2016" => "side-channel-attacks-on-everyday-applications"),
        page! {
            handler: research::side_channels_in_encoding_functions,
            slug: "side-channels-in-encoding-functions",
            title: "Side Channel Attacks in Hex and Base64 Encoding",
            description: "Do encoding functions like bin2hex and base64_encode create side channels?",
            keywords: "side channel, side channel attack, encoding, bin2hex, base64",
            legacy_hit_count_id: "pages/research/side-channels-in-encoding-functions.php",
            upvote: None,
        },
        page! {
            handler: research::softwaresecurity,
            slug: "softwaresecurity",
            title: "Software Security - Bypassing KeyScrambler and Avira - Defuse Security",
            description: "The fundamental flaw in the software security model. Bypassing KeyScrambler and Avira",
            keywords: "software security, antivirus, keyscrambler, antivir",
            legacy_hit_count_id: "pages/research/softwaresecurity.html",
            upvote: None,
        },
        page! {
            handler: research::ssl_fundamental_flaw_fix,
            slug: "ssl-fundamental-flaw-fix",
            title: "Fixing the Flaw in the SSL Certificate Authority Architecture - Defuse Security",
            description: "Dangers of the Internet, an explanation of the dangers you face online.",
            keywords: "",
            legacy_hit_count_id: "pages/research/ssl-fundamental-flaw-fix.html",
            upvote: None,
        },
        page! {
            handler: research::stopspying,
            slug: "stopspying",
            title: "Stop Spying! Bills C-50, C-51, C-52. Warrantless Wiretaps in Canada.",
            description: "canada, warrant-less wiretap, isp, c51, c52, c50, spying, law, bill, internet privacy",
            keywords: "",
            legacy_hit_count_id: "pages/research/stopspying.php",
            upvote: None,
        },
        page! {
            handler: research::manual_random_number_generator,
            slug: "manual-random-number-generator",
            title: "Manually Generating Random Numbers",
            description: "Manually generating random numbers for cryptographic use.",
            keywords: "random numbers, true random, csprng, cryptographically secure",
            legacy_hit_count_id: "pages/research/manual-random-number-generator.php",
            upvote: Some(UpvoteConfig {
                id: "manualrng",
                category: "defuse_pages",
                title: Some("A Manual Random Number Generator"),
                description: Some("Generating random numbers with paper coins."),
            }),
        },
        page! {
            handler: research::microsoft_reads_your_skype_messages,
            slug: "microsoft-reads-your-skype-messages",
            title: "Confirmation of H-Online's Skype Results: Microsoft Visits Links",
            description: "An independent confirmation of Microsoft's skype spying.",
            keywords: "h-online skype, skype spying, microsoft, skype security",
            legacy_hit_count_id: "pages/research/microsoft-reads-your-skype-messages.php",
            upvote: Some(UpvoteConfig {
                id: "skypemitm",
                category: "defuse_pages",
                title: Some("Confirmed: Microsoft Visits Links You Send In Skype"),
                description: Some("I sent a link through Skype and Microsoft visted it, confirming The H's claims."),
            }),
        },
        page! {
            handler: research::eotp,
            slug: "eotp",
            title: "Encrypting One Time Passwords System - Defuse Security",
            description: "A One Time Password protocol that can be used with encryption.",
            keywords: "encrypting one time passwords, static key, one time password",
            legacy_hit_count_id: "pages/research/eotp.html",
            upvote: Some(UpvoteConfig {
                id: "eotp",
                category: "defuse_pages",
                title: Some("Encrypting One Time Passwords (EOTP)"),
                description: Some("EOTP is a cryptographic One Time Password (OTP) protocol designed to provide a static encryption key across login sessions."),
            }),
        },
        page! {
            handler: research::triangle_of_secure_code_delivery,
            slug: "triangle-of-secure-code-delivery",
            title: "Triangle of Secure Code Delivery",
            description: "What's necessary and sufficient for delivering code securely?",
            keywords: "code delivery, triangle, reproducible build, signing",
            legacy_hit_count_id: "pages/research/triangle-of-secure-code-delivery.php",
            upvote: Some(UpvoteConfig {
                id: "trianglesecurecodedelivery",
                category: "defuse_pages",
                title: Some("Triangle of Secure Code Delivery"),
                description: Some("Three properties necessary and sufficient for delivering code safely."),
            }),
        },
        page! {
            handler: research::truecrypt_plausible_deniability_useless_by_game_theory,
            slug: "truecrypt-plausible-deniability-useless-by-game-theory",
            title: "TrueCrypt's Plausible Deniability (Hidden Volumes) is Theoretically Useless",
            description: "How game theory shows that TrueCrypt's hidden volume feature is provably useless in some scenarios.",
            keywords: "game theory, truecrypt plausible deniability",
            legacy_hit_count_id: "pages/research/truecrypt-plausible-deniability-useless-by-game-theory.php",
            upvote: Some(UpvoteConfig {
                id: "truecryptgametheory",
                category: "defuse_pages",
                title: Some("TrueCrypt's Plausible Deniability is Theoretically Useless"),
                description: Some("Why you really ought to have a hidden volume, even if you don't need one."),
            }),
        },
        page! {
            handler: research::web_application_security,
            slug: "web-application-security",
            title: "Web Application Security - Defuse Security",
            description: "Why are websites so insecure? What design patterns will help solve these problems?",
            keywords: "web application security, cross site scripting, sql injection, remote code execution, php, asp, scripting",
            legacy_hit_count_id: "pages/research/web-application-security.html",
            upvote: Some(UpvoteConfig {
                id: "webappsec",
                category: "defuse_pages",
                title: Some("Data Flow in Web Applications"),
                description: Some("A look at the flow of data in web applications and how it can be tamed for security."),
            }),
        },
        page! {
            handler: research::web_browser_javascript_cryptography,
            slug: "web-browser-javascript-cryptography",
            title: "Web Browser Cryptography is a Good Thing",
            description: "Arguments for and against doing cryptography in the browser.",
            keywords: "javascript cryptography, web browser cryptography, browser cryptography, encryption",
            legacy_hit_count_id: "pages/research/web-browser-javascript-cryptography.php",
            upvote: Some(UpvoteConfig {
                id: "webbrowsercryptography",
                category: "defuse_pages",
                title: Some("Web Browser Cryptography is a Good Thing"),
                description: Some("Why we should support the development of browser-based crypto applications."),
            }),
        },
        page! {
            handler: research::website_key_stretching_feasibility,
            slug: "website-key-stretching-feasibility",
            title: "Feasibility of Using Key Stretching in Web Applications",
            description: "How much does using key stretching to hash passwords cost? Is it reasonable?",
            keywords: "web application, key stretching feasibility, password hashing, cpu intensive hash function",
            legacy_hit_count_id: "pages/research/website-key-stretching-feasibility.php",
            upvote: None,
        },

        // ===== Miscellaneous =====
        page! {
            handler: misc::advice_to_aspiring_computer_engineers,
            slug: "advice-to-aspiring-computer-engineers",
            title: "Advice to Aspiring Computer Engineers and Scientists",
            description: "Advice for new computer science students.",
            keywords: "advice, computer science",
            legacy_hit_count_id: "pages/misc/advice-to-aspiring-computer-engineers.php",
            upvote: Some(UpvoteConfig {
                id: "advicetocs",
                category: "defuse_pages",
                title: Some("Advice to Aspiring Computer Security Engineers/Scientists"),
                description: Some("Some advice for new computer science students based on my experience."),
            }),
        },
        page! {
            handler: misc::centripetal_acceleration,
            slug: "centripetal-acceleration",
            title: "Centripetal Acceleration",
            description: "A derivation of the Centripetal Acceleration equation",
            keywords: "centripetal force, centripetal acceleration",
            legacy_hit_count_id: "pages/misc/centripetal-acceleration.php",
            upvote: Some(UpvoteConfig {
                id: "centripetalaccel",
                category: "defuse_pages",
                title: Some("Centripetal Acceleration"),
                description: Some("Deriving the centripetal acceleration equation."),
            }),
        },
        page! {
            handler: misc::contributors,
            slug: "contributors",
            title: "Contributors",
            description: "A list of people and organizations that have contributed to Defuse Security",
            keywords: "contribution, donation, thanks",
            legacy_hit_count_id: "pages/misc/contributors.php",
            upvote: None,
        },
        page! {
            handler: misc::fractal_zoom,
            slug: "fractal-zoom",
            title: "Fractal Zoom",
            description: "A psychedelic short story.",
            keywords: "fractal zoom, short story, sci-fi, psychedelic",
            legacy_hit_count_id: "pages/misc/fractal-zoom.php",
            upvote: Some(UpvoteConfig {
                id: "fractalzoom",
                category: "defuse_pages",
                title: Some("Fractal Zoom"),
                description: Some("A psychedelic short story."),
            }),
        },
        page! {
            handler: misc::ideas,
            slug: "ideas",
            title: "Ideas",
            description: "Lots of ideas.",
            keywords: "ideas, useless ideas, crazy ideas, list",
            legacy_hit_count_id: "pages/misc/ideas.php",
            upvote: None,
        },
        page! {
            handler: misc::known_unknowns,
            slug: "known-unknowns",
            title: "Known Unknowns",
            description: "Things that I am aware of which I do not understand.",
            keywords: "known unknowns, learning",
            legacy_hit_count_id: "pages/misc/known-unknowns.php",
            upvote: None,
        },
        page! {
            handler: misc::new_york_times_algebra,
            slug: "new-york-times-algebra",
            title: "Does the New York Times Fail at Algebra? (No.)",
            description: "The New York Times does not (necessarily) fail at algebra.",
            keywords: "new york times, the interview, algebra, sales",
            legacy_hit_count_id: "pages/misc/new-york-times-algebra.php",
            upvote: Some(UpvoteConfig {
                id: "newyorktimesalgebra",
                category: "defuse_pages",
                title: Some("The New York Times and Algebra"),
                description: Some("The New York Times does not (necessarily) fail at algebra."),
            }),
        },
        page! {
            handler: misc::pocorgtfo,
            slug: "pocorgtfo",
            title: "PoC || GTFO Mirror",
            description: "Mirror of all the Poc || GTFO issues.",
            keywords: "proof, of, concept, or, get, the, fuck, out",
            legacy_hit_count_id: "pages/misc/pocorgtfo.php",
            upvote: None,
        },
        page! {
            handler: misc::rules_for_working_with_me,
            slug: "rules-for-working-with-me",
            title: "Rules For Working With Me",
            description: "How to get along with me.",
            keywords: "employment, working with me, teamwork",
            legacy_hit_count_id: "pages/misc/rules-for-working-with-me.php",
            upvote: None,
        },
        page! {
            handler: misc::the_meaning_of_if,
            slug: "the-meaning-of-if",
            title: "The meaning of \"IF\" -- An Introduction to Formal Logic",
            description: "What the word \"If\" means in formal logic",
            keywords: "formal logic introduction, meaning of if, what if means",
            legacy_hit_count_id: "pages/misc/the-meaning-of-if.php",
            upvote: None,
        },
        page! {
            handler: misc::the_universe_is_made_of_cheese,
            slug: "the-universe-is-made-of-cheese",
            title: "The Universe is Made of Cheese - A Formal Proof",
            description: "A logical proof that the universe consists entirely of cheese.",
            keywords: "cheese paradox, universe made of cheese, logical proof",
            legacy_hit_count_id: "pages/misc/the-universe-is-made-of-cheese.php",
            upvote: Some(UpvoteConfig {
                id: "universeOfCheese",
                category: "defuse_pages",
                title: Some("The Cheese Universe Paradox"),
                description: Some("A formal proof that the universe is made entirely of cheese."),
            }),
        },
        page! {
            handler: misc::truecrypt_7_1a_hashes,
            slug: "truecrypt-7.1a-hashes",
            title: "TrueCrypt 7.1a Hashes",
            description: "SHA256 and SHA1 hashes of the last version of TrueCrypt.",
            keywords: "TrueCrypt, 7.1a, 7.1, SHA256, MD5, SHA1",
            legacy_hit_count_id: "pages/misc/truecrypt-7.1a-hashes.php",
            upvote: Some(UpvoteConfig {
                id: "truecrypthashes",
                category: "defuse_pages",
                title: None,
                description: None,
            }),
        },
        page! {
            handler: misc::x_plane_combat,
            slug: "x-plane-combat",
            title: "Combat in X-Plane: Weapon Setup, Enemy Aircraft, and Targeting",
            description: "How to fight in the X-Plane simulator.",
            keywords: "x-plane combat, fighter jet, flight simulator, weapon select, enemy aircraft",
            legacy_hit_count_id: "pages/misc/x-plane-combat.php",
            upvote: Some(UpvoteConfig {
                id: "xplanecombat",
                category: "defuse_pages",
                title: Some("Combat in X-Plane 10"),
                description: Some("How to configure X-Plane 10 for combat."),
            }),
        },
        page! {
            handler: misc::writing_tips,
            slug: "writing-tips",
            title: "Writing Tips",
            description: "Some tips to make your writing better.",
            keywords: "writing tips, good writing, clear writing",
            legacy_hit_count_id: "pages/misc/writing-tips.php",
            upvote: Some(UpvoteConfig {
                id: "writing_tips",
                category: "defuse_pages",
                title: Some("Writing Tips"),
                description: Some("Short tips to make your writing better."),
            }),
        },

        // ===== Projects =====
        page! {
            handler: projects::blowfish,
            slug: "blowfish",
            title: "Blowfish C# and C++ Source Code - Defuse Security",
            description: "C# and C++ implementation of the BLOWFISH block cipher.",
            keywords: "",
            legacy_hit_count_id: "pages/projects/blowfish.html",
            upvote: None,
        },
        page! {
            handler: projects::bochs_images,
            slug: "bochs-images",
            title: "Disk Images for the Bochs x86 Emulator",
            description: "Various operating systems installed on disk images for Bochs.",
            keywords: "",
            legacy_hit_count_id: "pages/projects/bochs-images.php",
            upvote: Some(UpvoteConfig {
                id: "bochsdiskimages",
                category: "defuse_pages",
                title: Some("Bochs Disk Images"),
                description: Some("Disk images for the Bochs x86 emulator."),
            }),
        },
        page! {
            handler: projects::email_spoofing_in_ruby,
            slug: "email-spoofing-in-ruby",
            title: "Spoofing SMTP email with a Ruby script - Defuse Security",
            description: "Example script for communicating with an SMTP server in Ruby to send spoofed email.",
            keywords: "email spoofing, smtp spoofing, ruby email, ruby smtp",
            legacy_hit_count_id: "pages/projects/email-spoofing-in-ruby.php",
            upvote: Some(UpvoteConfig {
                id: "email_spoofing_ruby",
                category: "defuse_pages",
                title: Some("Email Spoofing in Ruby"),
                description: Some("A Ruby script for spoofing email to SMTP servers."),
            }),
        },
        page! {
            handler: projects::force_print_background,
            slug: "force-print-background",
            title: "HTML/CSS Force Printing of Background Color - Defuse Security",
            description: "HTML/CSS Hack to get browsers to print background colors.",
            keywords: "print background color, html, css, force print background color, print stylesheet",
            legacy_hit_count_id: "pages/projects/force-print-background.php",
            upvote: Some(UpvoteConfig {
                id: "forceprinthtmlbg",
                category: "defuse_pages",
                title: Some("Forcing HTML/CSS Background Color to Print"),
                description: Some("How to force browsers to print the background color of HTML elements (using images)."),
            }),
        },
        page! {
            handler: projects::generating_random_passwords,
            slug: "generating-random-passwords",
            title: "Generating Unbiased Random Passwords in PHP",
            description: "Code for generating SECURE random passwords in PHP.",
            keywords: "generating passwords with php, generating passwords, php, random passwords",
            legacy_hit_count_id: "pages/projects/generating-random-passwords.php",
            upvote: Some(UpvoteConfig {
                id: "generatingrandompasswords",
                category: "defuse_pages",
                title: Some("Generating Random Passwords in PHP"),
                description: Some("How to generate unbiased passwords in PHP (plus some common mistakes)."),
            }),
        },
        page! {
            handler: projects::gnutls_psk_client_server_example,
            slug: "gnutls-psk-client-server-example",
            title: "GnuTLS Pre-Shared Key (PSK) Client-Server Example Code",
            description: "How to establish an SSL/TLS connection with GnuTLS and PSK authentication.",
            keywords: "gnutls, ssl, tls, https, client, server, psk, authentication",
            legacy_hit_count_id: "pages/projects/gnutls-psk-client-server-example.php",
            upvote: Some(UpvoteConfig {
                id: "gnutlspsk",
                category: "defuse_pages",
                title: Some("GnuTLS Pre-Shared Key Client-Server Example"),
                description: Some("How to establish an SSL/TLS connection with GnuTLS and PSK authentication."),
            }),
        },
        page! {
            handler: projects::gpucrack,
            slug: "gpucrack",
            title: "CUDA Salted MD5 GPU Cracker Source Code - Defuse Security",
            description: "Source code for a salted MD5 hash cracker using nvidia graphics cards (CUDA).",
            keywords: "salted md5, hash cracking, gpu, graphics cards, nvidia, cuda",
            legacy_hit_count_id: "pages/projects/gpucrack.html",
            upvote: None,
        },
        page! {
            handler: projects::inn_private_newsgroup_server_setup,
            slug: "inn-private-newsgroup-server-setup",
            title: "Configuring a Private (Local) News Server with INN2",
            description: "How to configure a private local newsgroup server (non-UseNet) on Debian",
            keywords: "inn2 configuration, news server configuration, local newsgroups, cecil-id, private newsgroups",
            legacy_hit_count_id: "pages/projects/inn-private-newsgroup-server-setup.php",
            upvote: None,
        },
        page! {
            handler: projects::online_free_computer_science_education,
            slug: "online-free-computer-science-education",
            title: "Computer Science Video Lecture Collection",
            description: "A collection of computer science related videos from various universities.",
            keywords: "computer science lecture, programming lecture, education, free education",
            legacy_hit_count_id: "pages/projects/online-free-computer-science-education.php",
            upvote: None,
        },
        page! {
            handler: projects::php_hit_counter,
            slug: "php-hit-counter",
            title: "PHP & MySQL Unique Hit Count Tracker - Defuse Security",
            description: "A unique hit counter for PHP. Tracks unique hits without storing the IP address.",
            keywords: "hit counter, php, secure, private, anonymous, unique hits, track",
            legacy_hit_count_id: "pages/projects/php-hit-counter.html",
            upvote: Some(UpvoteConfig {
                id: "phphitcounter",
                category: "defuse_pages",
                title: Some("\"Privacy Aware\" Unique Hit Counter for PHP"),
                description: Some("A simple hit counter that stores only a hash of your visitor's IP address."),
            }),
        },
        page! {
            handler: projects::php_pbkdf2,
            slug: "php-pbkdf2",
            title: "PBKDF2 Password Hashing for PHP",
            description: "Standards compliant PBKDF2 implementation for PHP.",
            keywords: "pbkdf2 for php, key derivation, password hashing",
            legacy_hit_count_id: "pages/projects/php-pbkdf2.php",
            upvote: Some(UpvoteConfig {
                id: "phppbkdf2",
                category: "defuse_pages",
                title: Some("PBKDF2 for PHP"),
                description: Some("A fast implementation of the PBKDF2 key stretching function in PHP."),
            }),
        },
        page! {
            handler: projects::projects,
            slug: "projects",
            title: "Defuse Security's Projects",
            description: "All of Defuse Security's projects.",
            keywords: "security, computer security, projects",
            legacy_hit_count_id: "pages/projects/projects.html",
            upvote: None,
        },
        page! {
            handler: projects::secure_php_encryption,
            slug: "secure-php-encryption",
            title: "Encrypting Data in PHP (HowTo) - Defuse Security",
            description: "Source code for encrypting data in PHP with mcrypt. The right way to do it.",
            keywords: "php encrypiton, php aes, encryption in php, php decryption",
            legacy_hit_count_id: "pages/projects/secure-php-encryption.php",
            upvote: Some(UpvoteConfig {
                id: "securephpencryption",
                category: "defuse_pages",
                title: Some("How to Encrypt Data in PHP"),
                description: Some("The right way to encrypt data in PHP."),
            }),
        },
        page! {
            handler: projects::syntax_highlighting_in_php_with_vim,
            slug: "syntax-highlighting-in-php-with-vim",
            title: "Scripting Vim's HTML syntax highlighting in PHP",
            description: "Using the Vim editor to highlight code syntax from PHP",
            keywords: "",
            legacy_hit_count_id: "pages/projects/syntax-highlighting-in-php-with-vim.php",
            upvote: Some(UpvoteConfig {
                id: "syntaxhighlightingvim",
                category: "defuse_pages",
                title: Some("Using the Vim Editor for Syntax Highlighting in PHP"),
                description: Some("Generate syntax-highlighted code automatically in PHP with Vim."),
            }),
        },
        page! {
            handler: projects::web_browser_negative_feedback,
            slug: "web-browser-negative-feedback",
            title: "Negative Feedback for Insecure Connections",
            description: "Should web browser interfaces provide negative feedback when the connection is insecure?",
            keywords: "negative feedback, insecure connections, http, https, ssl, tls, ev",
            legacy_hit_count_id: "pages/projects/web-browser-negative-feedback.php",
            upvote: None,
        },
        page! {
            handler: projects::wordlists,
            slug: "wordlists",
            title: "Password Cracking Wordlists - Defuse Security",
            description: "The best password cracking wordlists and dictionaries on the internet.",
            keywords: "password cracking, word list, wordlist, dictionary, md5, hash cracking",
            legacy_hit_count_id: "pages/projects/wordlists.html",
            upvote: None,
        },

        // ===== Software =====
        page! {
            handler: software::backup_verify_script,
            slug: "backup-verify-script",
            title: "Script for Comparing Folders and Validating Backups",
            description: "A command-line script for verifying backups by comparing two folders in Linux",
            keywords: "backup validate, backup verify, compare folders, linux, ruby",
            legacy_hit_count_id: "pages/software/backup-verify-script.php",
            upvote: Some(UpvoteConfig {
                id: "backupverifyscript",
                category: "defuse_pages",
                title: Some("Backup Verifier Script (Ruby)"),
                description: Some("A Ruby script that compares two directories and reports the differences."),
            }),
        },
        page! {
            handler: software::helloworld_cms,
            slug: "helloworld-cms",
            title: "Secure and Light CMS for PHP - Defuse Security",
            description: "A lightweight, ultra-secure CMS for PHP",
            keywords: "secure cms, php cms, light cms, small cms, tiny cms, cms",
            legacy_hit_count_id: "pages/software/helloworld-cms.html",
            upvote: Some(UpvoteConfig {
                id: "helloworld",
                category: "defuse_pages",
                title: Some("HelloWorld! - A Light & Secure CDS for PHP"),
                description: Some("A lightweight, ultra-secure, CMS/CDS for PHP"),
            }),
        },
        page! {
            handler: software::software,
            slug: "software",
            title: "Defuse Security's Software",
            description: "Software created by Defuse Security",
            keywords: "",
            legacy_hit_count_id: "pages/software/software.html",
            upvote: None,
        },
        page! {
            handler: software::php_hash_cracker,
            slug: "php-hash-cracker",
            title: "Salted Hash Cracking PHP Script - Defuse Security",
            description: "Dictionary hash cracking PHP scripts (supports LOTS of hash types!!)",
            keywords: "hash cracking, dictionary attack, php hash cracking script",
            legacy_hit_count_id: "pages/software/php-hash-cracker.php",
            upvote: Some(UpvoteConfig {
                id: "phphashcracker",
                category: "defuse_pages",
                title: Some("Salted Hash Cracking PHP Script"),
                description: Some("A script for cracking hashes when all you have is PHP."),
            }),
        },
        page! {
            handler: software::sockstress,
            slug: "sockstress",
            title: "Sockstress Denial of Service Tool & Source Code - Defuse Security",
            description: "A C implementation of the sockstress attack from 2008.",
            keywords: "sockstress, source code, denial of service, proof of concept, dos, ddos",
            legacy_hit_count_id: "pages/software/sockstress.php",
            upvote: Some(UpvoteConfig {
                id: "sockstress",
                category: "defuse_pages",
                title: Some("Sockstress DoS Tool"),
                description: Some("A public domain C implementation of the sockstress DoS attack."),
            }),
        },
        page! {
            handler: software::winrrng,
            slug: "winrrng",
            title: "Real Random Number Generator for Windows - Defuse Security",
            description: "A real random number generator for Windows",
            keywords: "",
            legacy_hit_count_id: "pages/software/winrrng.html",
            upvote: None,
        },

        // ===== Audits =====
        page! {
            handler: audits::encfs,
            slug: "audits/encfs",
            title: "EncFS Security Audit",
            description: "Security audit of the EncFS encrypted filesystem.",
            keywords: "encfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/encfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditencfs",
                category: "defuse_pages",
                title: Some("EncFS Security Audit"),
                description: Some("The results of an EncFS security audit."),
            }),
        },
        page! {
            handler: audits::encfs_old,
            slug: "audits/encfs-old",
            title: "EncFS Security Audit",
            description: "Security audit of the EncFS encrypted filesystem.",
            keywords: "encfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/encfs-old.php",
            upvote: Some(UpvoteConfig {
                id: "auditencfsOLD",
                category: "defuse_pages",
                title: Some("EncFS Security Audit"),
                description: Some("The results of an EncFS security audit."),
            }),
        },
        page! {
            handler: audits::ecryptfs,
            slug: "audits/ecryptfs",
            title: "eCryptfs Security Audit",
            description: "Security audit of the eCryptfs encrypted filesystem.",
            keywords: "eCryptfs, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/ecryptfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditecryptfs",
                category: "defuse_pages",
                title: Some("eCryptfs Security Audit"),
                description: Some("The results of an eCryptfs security audit."),
            }),
        },
        page! {
            handler: audits::pefs,
            slug: "audits/pefs",
            title: "PEFS Security Audit",
            description: "Security audit of the PEFS encrypted filesystem.",
            keywords: "PEFS, security audit, cryptography",
            legacy_hit_count_id: "pages/audits/pefs.php",
            upvote: Some(UpvoteConfig {
                id: "auditpefs",
                category: "defuse_pages",
                title: Some("PEFS Security Audit"),
                description: Some("Security audit of the Private Encrypted File System (PEFS)."),
            }),
        },
        page! {
            handler: audits::zerobin,
            slug: "audits/zerobin",
            title: "ZeroBin Security Audit",
            description: "Security audit of the ZeroBin Zero-Knowledge Pastebin",
            keywords: "secure pastebin, security audit, zerobin",
            legacy_hit_count_id: "pages/audits/zerobin.php",
            upvote: Some(UpvoteConfig {
                id: "auditzerobin",
                category: "defuse_pages",
                title: Some("ZeroBin Security Audit"),
                description: Some("A security audit of the ZeroBin pastebin."),
            }),
        },
        page! {
            handler: audits::gocryptfs,
            slug: "audits/gocryptfs",
            title: "Gocryptfs Security Audit",
            description: "Security audit of the gocryptfs encrypted filesystem",
            keywords: "gocryptfs, encrypted filesystem, security audit ",
            legacy_hit_count_id: "pages/audits/gocryptfs.php",
            upvote: Some(UpvoteConfig {
                id: "auditgocryptfs0",
                category: "defuse_pages",
                title: Some("Gocryptfs Security Audit"),
                description: Some("A security audit of the gocryptfs encrypted filesystem."),
            }),
        },
        page! {
            handler: audits::hash0,
            slug: "audits/hash0",
            title: "Hash0 Security Audit",
            description: "Security audit of the Hash0 password system",
            keywords: "hash0, security audit, cryptography, passwords",
            legacy_hit_count_id: "pages/audits/hash0.php",
            upvote: Some(UpvoteConfig {
                id: "audithashzero",
                category: "defuse_pages",
                title: Some("Hash0 Security Audit"),
                description: Some("A security audit of the Hash0 pastebin."),
            }),
        },

        // ===== Test pages =====
        page! {
            handler: panic_test,
            slug: "panic-test",
            title: "Panic Test",
            description: "Test page that panics during rendering.",
            keywords: "",
            legacy_hit_count_id: "",
            upvote: None,
        },
    ];

    // Build HashMap with lowercase keys for case-insensitive lookup
    pages
        .iter()
        .map(|p| (p.slug.to_lowercase().leak() as &'static str, p.clone()))
        .collect()
});
